/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_BarometricPressure_H_
#define	_srem_BarometricPressure_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_BarometricPressure {
	srem_BarometricPressure_outOfRangelower	= 2999,
	srem_BarometricPressure_outOfRangeUpper	= 12001,
	srem_BarometricPressure_unavailable	= 12002
} e_srem_BarometricPressure;

/* srem_BarometricPressure */
typedef long	 srem_BarometricPressure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_BarometricPressure;
asn_struct_free_f srem_BarometricPressure_free;
asn_struct_print_f srem_BarometricPressure_print;
asn_constr_check_f srem_BarometricPressure_constraint;
jer_type_encoder_f srem_BarometricPressure_encode_jer;
per_type_decoder_f srem_BarometricPressure_decode_uper;
per_type_encoder_f srem_BarometricPressure_encode_uper;
per_type_decoder_f srem_BarometricPressure_decode_aper;
per_type_encoder_f srem_BarometricPressure_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_BarometricPressure_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
