/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ParkingReservationType_H_
#define	_srem_ParkingReservationType_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ParkingReservationType {
	srem_ParkingReservationType_disabled	= 0,
	srem_ParkingReservationType_pregnant	= 1,
	srem_ParkingReservationType_womenOnly	= 2,
	srem_ParkingReservationType_parentAndChild	= 3,
	srem_ParkingReservationType_loadAndOffloadGoods	= 4,
	srem_ParkingReservationType_manualElectricVehicleCharging	= 5,
	srem_ParkingReservationType_automatedElectricVehicleCharging	= 6,
	srem_ParkingReservationType_refriferatedTransport	= 7,
	srem_ParkingReservationType_vip	= 8,
	srem_ParkingReservationType_preBooking	= 9,
	srem_ParkingReservationType_freeToBeReserved	= 10,
	srem_ParkingReservationType_reservationNotPossible	= 11,
	srem_ParkingReservationType_automatedValetparking	= 12,
	srem_ParkingReservationType_permit	= 13,
	srem_ParkingReservationType_unmarked	= 14
} e_srem_ParkingReservationType;

/* srem_ParkingReservationType */
typedef long	 srem_ParkingReservationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ParkingReservationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ParkingReservationType;
asn_struct_free_f srem_ParkingReservationType_free;
asn_struct_print_f srem_ParkingReservationType_print;
asn_constr_check_f srem_ParkingReservationType_constraint;
jer_type_encoder_f srem_ParkingReservationType_encode_jer;
per_type_decoder_f srem_ParkingReservationType_decode_uper;
per_type_encoder_f srem_ParkingReservationType_encode_uper;
per_type_decoder_f srem_ParkingReservationType_decode_aper;
per_type_encoder_f srem_ParkingReservationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ParkingReservationType_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
