/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_MessageId_H_
#define	_srem_MessageId_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_MessageId {
	srem_MessageId_denm	= 1,
	srem_MessageId_cam	= 2,
	srem_MessageId_poim	= 3,
	srem_MessageId_spatem	= 4,
	srem_MessageId_mapem	= 5,
	srem_MessageId_ivim	= 6,
	srem_MessageId_rfu1	= 7,
	srem_MessageId_rfu2	= 8,
	srem_MessageId_srem	= 9,
	srem_MessageId_ssem	= 10,
	srem_MessageId_evcsn	= 11,
	srem_MessageId_saem	= 12,
	srem_MessageId_rtcmem	= 13,
	srem_MessageId_cpm	= 14,
	srem_MessageId_imzm	= 15,
	srem_MessageId_vam	= 16,
	srem_MessageId_dsm	= 17,
	srem_MessageId_mim	= 18,
	srem_MessageId_mvm	= 19,
	srem_MessageId_mcm	= 20,
	srem_MessageId_pim	= 21
} e_srem_MessageId;

/* srem_MessageId */
typedef long	 srem_MessageId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_MessageId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_MessageId;
asn_struct_free_f srem_MessageId_free;
asn_struct_print_f srem_MessageId_print;
asn_constr_check_f srem_MessageId_constraint;
jer_type_encoder_f srem_MessageId_encode_jer;
per_type_decoder_f srem_MessageId_decode_uper;
per_type_encoder_f srem_MessageId_encode_uper;
per_type_decoder_f srem_MessageId_decode_aper;
per_type_encoder_f srem_MessageId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_MessageId_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
