/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_H_
#define	_srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ETSI_ITS_DSRC_PrioritizationResponseStatus {
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_unknown	= 0,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_requested	= 1,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_processing	= 2,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_watchOtherTraffic	= 3,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_granted	= 4,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_rejected	= 5,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_maxPresence	= 6,
	srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_reserviceLocked	= 7
	/*
	 * Enumeration is extensible
	 */
} e_srem_ETSI_ITS_DSRC_PrioritizationResponseStatus;

/* srem_ETSI-ITS-DSRC_PrioritizationResponseStatus */
typedef long	 srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_DSRC_PrioritizationResponseStatus;
extern const asn_INTEGER_specifics_t asn_SPC_srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_specs_1;
asn_struct_free_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_free;
asn_struct_print_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_print;
asn_constr_check_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_constraint;
jer_type_encoder_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_encode_jer;
per_type_decoder_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_decode_uper;
per_type_encoder_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_encode_uper;
per_type_decoder_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_decode_aper;
per_type_encoder_f srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_DSRC_PrioritizationResponseStatus_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
