/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ITS_Container_AltitudeValue_H_
#define	_srem_ITS_Container_AltitudeValue_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ITS_Container_AltitudeValue {
	srem_ITS_Container_AltitudeValue_referenceEllipsoidSurface	= 0,
	srem_ITS_Container_AltitudeValue_oneCentimeter	= 1,
	srem_ITS_Container_AltitudeValue_unavailable	= 800001
} e_srem_ITS_Container_AltitudeValue;

/* srem_ITS-Container_AltitudeValue */
typedef long	 srem_ITS_Container_AltitudeValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ITS_Container_AltitudeValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ITS_Container_AltitudeValue;
asn_struct_free_f srem_ITS_Container_AltitudeValue_free;
asn_struct_print_f srem_ITS_Container_AltitudeValue_print;
asn_constr_check_f srem_ITS_Container_AltitudeValue_constraint;
jer_type_encoder_f srem_ITS_Container_AltitudeValue_encode_jer;
per_type_decoder_f srem_ITS_Container_AltitudeValue_decode_uper;
per_type_encoder_f srem_ITS_Container_AltitudeValue_encode_uper;
per_type_decoder_f srem_ITS_Container_AltitudeValue_decode_aper;
per_type_encoder_f srem_ITS_Container_AltitudeValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ITS_Container_AltitudeValue_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
