/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_TracesExtended_H_
#define	_srem_TracesExtended_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_PathExtended;

/* srem_TracesExtended */
typedef struct srem_TracesExtended {
	A_SEQUENCE_OF(struct srem_PathExtended) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_TracesExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_TracesExtended;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_PathExtended.h"

#endif	/* _srem_TracesExtended_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
