/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_VehicleRole_H_
#define	_srem_ETSI_ITS_CDD_VehicleRole_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ETSI_ITS_CDD_VehicleRole {
	srem_ETSI_ITS_CDD_VehicleRole_default	= 0,
	srem_ETSI_ITS_CDD_VehicleRole_publicTransport	= 1,
	srem_ETSI_ITS_CDD_VehicleRole_specialTransport	= 2,
	srem_ETSI_ITS_CDD_VehicleRole_dangerousGoods	= 3,
	srem_ETSI_ITS_CDD_VehicleRole_roadWork	= 4,
	srem_ETSI_ITS_CDD_VehicleRole_rescue	= 5,
	srem_ETSI_ITS_CDD_VehicleRole_emergency	= 6,
	srem_ETSI_ITS_CDD_VehicleRole_safetyCar	= 7,
	srem_ETSI_ITS_CDD_VehicleRole_agriculture	= 8,
	srem_ETSI_ITS_CDD_VehicleRole_commercial	= 9,
	srem_ETSI_ITS_CDD_VehicleRole_military	= 10,
	srem_ETSI_ITS_CDD_VehicleRole_roadOperator	= 11,
	srem_ETSI_ITS_CDD_VehicleRole_taxi	= 12,
	srem_ETSI_ITS_CDD_VehicleRole_uvar	= 13,
	srem_ETSI_ITS_CDD_VehicleRole_rfu1	= 14,
	srem_ETSI_ITS_CDD_VehicleRole_rfu2	= 15
} e_srem_ETSI_ITS_CDD_VehicleRole;

/* srem_ETSI-ITS-CDD_VehicleRole */
typedef long	 srem_ETSI_ITS_CDD_VehicleRole_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_VehicleRole;
asn_struct_free_f srem_ETSI_ITS_CDD_VehicleRole_free;
asn_struct_print_f srem_ETSI_ITS_CDD_VehicleRole_print;
asn_constr_check_f srem_ETSI_ITS_CDD_VehicleRole_constraint;
jer_type_encoder_f srem_ETSI_ITS_CDD_VehicleRole_encode_jer;
per_type_decoder_f srem_ETSI_ITS_CDD_VehicleRole_decode_uper;
per_type_encoder_f srem_ETSI_ITS_CDD_VehicleRole_encode_uper;
per_type_decoder_f srem_ETSI_ITS_CDD_VehicleRole_decode_aper;
per_type_encoder_f srem_ETSI_ITS_CDD_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_VehicleRole_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
