/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_SteeringWheelAngle_H_
#define	_srem_ETSI_ITS_CDD_SteeringWheelAngle_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_SteeringWheelAngleValue.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_SteeringWheelAngleConfidence.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ETSI-ITS-CDD_SteeringWheelAngle */
typedef struct srem_ETSI_ITS_CDD_SteeringWheelAngle {
	srem_ETSI_ITS_CDD_SteeringWheelAngleValue_t	 steeringWheelAngleValue;
	srem_ETSI_ITS_CDD_SteeringWheelAngleConfidence_t	 steeringWheelAngleConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ETSI_ITS_CDD_SteeringWheelAngle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_SteeringWheelAngle;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_SteeringWheelAngle_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
