/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_RequestImportanceLevel_H_
#define	_srem_ts_RequestImportanceLevel_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ts_RequestImportanceLevel {
	srem_ts_RequestImportanceLevel_requestImportanceLevelUnKnown	= 0,
	srem_ts_RequestImportanceLevel_requestImportanceLevel1	= 1,
	srem_ts_RequestImportanceLevel_requestImportanceLevel2	= 2,
	srem_ts_RequestImportanceLevel_requestImportanceLevel3	= 3,
	srem_ts_RequestImportanceLevel_requestImportanceLevel4	= 4,
	srem_ts_RequestImportanceLevel_requestImportanceLevel5	= 5,
	srem_ts_RequestImportanceLevel_requestImportanceLevel6	= 6,
	srem_ts_RequestImportanceLevel_requestImportanceLevel7	= 7,
	srem_ts_RequestImportanceLevel_requestImportanceLevel8	= 8,
	srem_ts_RequestImportanceLevel_requestImportanceLevel9	= 9,
	srem_ts_RequestImportanceLevel_requestImportanceLevel10	= 10,
	srem_ts_RequestImportanceLevel_requestImportanceLevel11	= 11,
	srem_ts_RequestImportanceLevel_requestImportanceLevel12	= 12,
	srem_ts_RequestImportanceLevel_requestImportanceLevel13	= 13,
	srem_ts_RequestImportanceLevel_requestImportanceLevel14	= 14,
	srem_ts_RequestImportanceLevel_requestImportanceReserved	= 15
} e_srem_ts_RequestImportanceLevel;

/* srem_ts_RequestImportanceLevel */
typedef long	 srem_ts_RequestImportanceLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ts_RequestImportanceLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_RequestImportanceLevel;
extern const asn_INTEGER_specifics_t asn_SPC_srem_ts_RequestImportanceLevel_specs_1;
asn_struct_free_f srem_ts_RequestImportanceLevel_free;
asn_struct_print_f srem_ts_RequestImportanceLevel_print;
asn_constr_check_f srem_ts_RequestImportanceLevel_constraint;
jer_type_encoder_f srem_ts_RequestImportanceLevel_encode_jer;
per_type_decoder_f srem_ts_RequestImportanceLevel_decode_uper;
per_type_encoder_f srem_ts_RequestImportanceLevel_encode_uper;
per_type_decoder_f srem_ts_RequestImportanceLevel_decode_aper;
per_type_encoder_f srem_ts_RequestImportanceLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_RequestImportanceLevel_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
