/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ObjectFace_H_
#define	_srem_ObjectFace_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ObjectFace {
	srem_ObjectFace_front	= 0,
	srem_ObjectFace_sideLeftFront	= 1,
	srem_ObjectFace_sideLeftBack	= 2,
	srem_ObjectFace_sideRightFront	= 3,
	srem_ObjectFace_sideRightBack	= 4,
	srem_ObjectFace_back	= 5
} e_srem_ObjectFace;

/* srem_ObjectFace */
typedef long	 srem_ObjectFace_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ObjectFace;
asn_struct_free_f srem_ObjectFace_free;
asn_struct_print_f srem_ObjectFace_print;
asn_constr_check_f srem_ObjectFace_constraint;
jer_type_encoder_f srem_ObjectFace_encode_jer;
per_type_decoder_f srem_ObjectFace_decode_uper;
per_type_encoder_f srem_ObjectFace_encode_uper;
per_type_decoder_f srem_ObjectFace_decode_aper;
per_type_encoder_f srem_ObjectFace_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ObjectFace_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
