/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_VruDeviceUsage_H_
#define	_srem_VruDeviceUsage_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_VruDeviceUsage {
	srem_VruDeviceUsage_unavailable	= 0,
	srem_VruDeviceUsage_other	= 1,
	srem_VruDeviceUsage_idle	= 2,
	srem_VruDeviceUsage_listeningToAudio	= 3,
	srem_VruDeviceUsage_typing	= 4,
	srem_VruDeviceUsage_calling	= 5,
	srem_VruDeviceUsage_playingGames	= 6,
	srem_VruDeviceUsage_reading	= 7,
	srem_VruDeviceUsage_viewing	= 8
} e_srem_VruDeviceUsage;

/* srem_VruDeviceUsage */
typedef long	 srem_VruDeviceUsage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_VruDeviceUsage;
asn_struct_free_f srem_VruDeviceUsage_free;
asn_struct_print_f srem_VruDeviceUsage_print;
asn_constr_check_f srem_VruDeviceUsage_constraint;
jer_type_encoder_f srem_VruDeviceUsage_encode_jer;
per_type_decoder_f srem_VruDeviceUsage_decode_uper;
per_type_encoder_f srem_VruDeviceUsage_encode_uper;
per_type_decoder_f srem_VruDeviceUsage_decode_aper;
per_type_encoder_f srem_VruDeviceUsage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_VruDeviceUsage_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
