/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_EmissionType_H_
#define	_srem_EmissionType_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_EmissionType {
	srem_EmissionType_euro1	= 0,
	srem_EmissionType_euro2	= 1,
	srem_EmissionType_euro3	= 2,
	srem_EmissionType_euro4	= 3,
	srem_EmissionType_euro5	= 4,
	srem_EmissionType_euro6	= 5
	/*
	 * Enumeration is extensible
	 */
} e_srem_EmissionType;

/* srem_EmissionType */
typedef long	 srem_EmissionType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_EmissionType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_EmissionType;
extern const asn_INTEGER_specifics_t asn_SPC_srem_EmissionType_specs_1;
asn_struct_free_f srem_EmissionType_free;
asn_struct_print_f srem_EmissionType_print;
asn_constr_check_f srem_EmissionType_constraint;
jer_type_encoder_f srem_EmissionType_encode_jer;
per_type_decoder_f srem_EmissionType_decode_uper;
per_type_encoder_f srem_EmissionType_encode_uper;
per_type_decoder_f srem_EmissionType_decode_aper;
per_type_encoder_f srem_EmissionType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_EmissionType_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
