/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_PathDeltaTimeChoice_H_
#define	_srem_PathDeltaTimeChoice_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_DeltaTimeTenthOfSecond.h"
#include "etsi_its_srem_ts_coding/srem_DeltaTimeTenSeconds.h"
#include "etsi_its_srem_ts_coding/srem_DeltaTimeSecond.h"
#include <etsi_its_srem_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_PathDeltaTimeChoice_PR {
	srem_PathDeltaTimeChoice_PR_NOTHING,	/* No components present */
	srem_PathDeltaTimeChoice_PR_deltaTimeHighPrecision,
	srem_PathDeltaTimeChoice_PR_deltaTimeBigRange,
	/* Extensions may appear below */
	srem_PathDeltaTimeChoice_PR_deltaTimeMidRange
} srem_PathDeltaTimeChoice_PR;

/* srem_PathDeltaTimeChoice */
typedef struct srem_PathDeltaTimeChoice {
	srem_PathDeltaTimeChoice_PR present;
	union srem_PathDeltaTimeChoice_u {
		srem_DeltaTimeTenthOfSecond_t	 deltaTimeHighPrecision;
		srem_DeltaTimeTenSeconds_t	 deltaTimeBigRange;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		srem_DeltaTimeSecond_t	 deltaTimeMidRange;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_PathDeltaTimeChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_PathDeltaTimeChoice;
extern asn_CHOICE_specifics_t asn_SPC_srem_PathDeltaTimeChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_PathDeltaTimeChoice_1[3];
extern asn_per_constraints_t asn_PER_type_srem_PathDeltaTimeChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_PathDeltaTimeChoice_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
