/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_VruEnvironment_H_
#define	_srem_VruEnvironment_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_VruEnvironment {
	srem_VruEnvironment_unavailable	= 0,
	srem_VruEnvironment_intersectionCrossing	= 1,
	srem_VruEnvironment_zebraCrossing	= 2,
	srem_VruEnvironment_sidewalk	= 3,
	srem_VruEnvironment_onVehicleRoad	= 4,
	srem_VruEnvironment_protectedGeographicArea	= 5
} e_srem_VruEnvironment;

/* srem_VruEnvironment */
typedef long	 srem_VruEnvironment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_VruEnvironment;
asn_struct_free_f srem_VruEnvironment_free;
asn_struct_print_f srem_VruEnvironment_print;
asn_constr_check_f srem_VruEnvironment_constraint;
jer_type_encoder_f srem_VruEnvironment_encode_jer;
per_type_decoder_f srem_VruEnvironment_decode_uper;
per_type_encoder_f srem_VruEnvironment_encode_uper;
per_type_decoder_f srem_VruEnvironment_decode_aper;
per_type_encoder_f srem_VruEnvironment_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_VruEnvironment_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
