/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_RectangularShape_H_
#define	_srem_RectangularShape_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_StandardLength12b.h"
#include "etsi_its_srem_ts_coding/srem_CartesianAngleValue.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_CartesianPosition3d;

/* srem_RectangularShape */
typedef struct srem_RectangularShape {
	struct srem_CartesianPosition3d	*shapeReferencePoint;	/* OPTIONAL */
	srem_StandardLength12b_t	 semiLength;
	srem_StandardLength12b_t	 semiBreadth;
	srem_CartesianAngleValue_t	*orientation;	/* OPTIONAL */
	srem_StandardLength12b_t	*height;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_RectangularShape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_RectangularShape;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_RectangularShape_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_RectangularShape_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_CartesianPosition3d.h"

#endif	/* _srem_RectangularShape_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
