/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_DSRC_MovementState_H_
#define	_srem_ETSI_ITS_DSRC_MovementState_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_DescriptiveName.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_SignalGroupID.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_MovementEventList.h"
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_ManeuverAssistList;
struct srem_Reg_MovementState;

/* srem_ETSI-ITS-DSRC_MovementState */
typedef struct srem_ETSI_ITS_DSRC_MovementState {
	srem_ETSI_ITS_DSRC_DescriptiveName_t	*movementName;	/* OPTIONAL */
	srem_ETSI_ITS_DSRC_SignalGroupID_t	 signalGroup;
	srem_ETSI_ITS_DSRC_MovementEventList_t	 state_time_speed;
	struct srem_ManeuverAssistList	*maneuverAssistList;	/* OPTIONAL */
	struct srem_ETSI_ITS_DSRC_MovementState__regional {
		A_SEQUENCE_OF(struct srem_Reg_MovementState) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ETSI_ITS_DSRC_MovementState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_DSRC_MovementState;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ETSI_ITS_DSRC_MovementState_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ETSI_ITS_DSRC_MovementState_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_ManeuverAssistList.h"
#include "etsi_its_srem_ts_coding/srem_RegionalExtension.h"

#endif	/* _srem_ETSI_ITS_DSRC_MovementState_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
