/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ExceptionalCondition_H_
#define	_srem_ExceptionalCondition_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ExceptionalCondition {
	srem_ExceptionalCondition_unknown	= 0,
	srem_ExceptionalCondition_publicTransportPriority	= 1,
	srem_ExceptionalCondition_emergencyVehiclePriority	= 2,
	srem_ExceptionalCondition_trainPriority	= 3,
	srem_ExceptionalCondition_bridgeOpen	= 4,
	srem_ExceptionalCondition_vehicleHeight	= 5,
	srem_ExceptionalCondition_weather	= 6,
	srem_ExceptionalCondition_trafficJam	= 7,
	srem_ExceptionalCondition_tunnelClosure	= 8,
	srem_ExceptionalCondition_meteringActive	= 9,
	srem_ExceptionalCondition_truckPriority	= 10,
	srem_ExceptionalCondition_bicyclePlatoonPriority	= 11,
	srem_ExceptionalCondition_vehiclePlatoonPriority	= 12
	/*
	 * Enumeration is extensible
	 */
} e_srem_ExceptionalCondition;

/* srem_ExceptionalCondition */
typedef long	 srem_ExceptionalCondition_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ExceptionalCondition_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ExceptionalCondition;
extern const asn_INTEGER_specifics_t asn_SPC_srem_ExceptionalCondition_specs_1;
asn_struct_free_f srem_ExceptionalCondition_free;
asn_struct_print_f srem_ExceptionalCondition_print;
asn_constr_check_f srem_ExceptionalCondition_constraint;
jer_type_encoder_f srem_ExceptionalCondition_encode_jer;
per_type_decoder_f srem_ExceptionalCondition_decode_uper;
per_type_encoder_f srem_ExceptionalCondition_encode_uper;
per_type_decoder_f srem_ExceptionalCondition_decode_aper;
per_type_encoder_f srem_ExceptionalCondition_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ExceptionalCondition_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
