/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_CorrelationCellValue_H_
#define	_srem_CorrelationCellValue_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_CorrelationCellValue {
	srem_CorrelationCellValue_full_negative_correlation	= -100,
	srem_CorrelationCellValue_no_correlation	= 0,
	srem_CorrelationCellValue_full_positive_correlation	= 100,
	srem_CorrelationCellValue_unavailable	= 101
} e_srem_CorrelationCellValue;

/* srem_CorrelationCellValue */
typedef long	 srem_CorrelationCellValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_CorrelationCellValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_CorrelationCellValue;
asn_struct_free_f srem_CorrelationCellValue_free;
asn_struct_print_f srem_CorrelationCellValue_print;
asn_constr_check_f srem_CorrelationCellValue_constraint;
jer_type_encoder_f srem_CorrelationCellValue_encode_jer;
per_type_decoder_f srem_CorrelationCellValue_decode_uper;
per_type_encoder_f srem_CorrelationCellValue_encode_uper;
per_type_decoder_f srem_CorrelationCellValue_decode_aper;
per_type_encoder_f srem_CorrelationCellValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_CorrelationCellValue_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
