/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_PathExtended_H_
#define	_srem_PathExtended_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>
#include "etsi_its_srem_ts_coding/srem_Path.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_PathExtended */
typedef struct srem_PathExtended {
	long	 pointOfEventZone;
	srem_Path_t	 path;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_PathExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_PathExtended;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_PathExtended_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_PathExtended_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _srem_PathExtended_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
