/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_WMInumber_H_
#define	_srem_ETSI_ITS_CDD_WMInumber_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ETSI-ITS-CDD_WMInumber */
typedef IA5String_t	 srem_ETSI_ITS_CDD_WMInumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ETSI_ITS_CDD_WMInumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_WMInumber;
asn_struct_free_f srem_ETSI_ITS_CDD_WMInumber_free;
asn_struct_print_f srem_ETSI_ITS_CDD_WMInumber_print;
asn_constr_check_f srem_ETSI_ITS_CDD_WMInumber_constraint;
jer_type_encoder_f srem_ETSI_ITS_CDD_WMInumber_encode_jer;
per_type_decoder_f srem_ETSI_ITS_CDD_WMInumber_decode_uper;
per_type_encoder_f srem_ETSI_ITS_CDD_WMInumber_encode_uper;
per_type_decoder_f srem_ETSI_ITS_CDD_WMInumber_decode_aper;
per_type_encoder_f srem_ETSI_ITS_CDD_WMInumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_WMInumber_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
