/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_DSRC_SpeedandHeadingandThrottleConfidence_H_
#define	_srem_DSRC_SpeedandHeadingandThrottleConfidence_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_DSRC_HeadingConfidenceDSRC.h"
#include "etsi_its_srem_ts_coding/srem_DSRC_SpeedConfidenceDSRC.h"
#include "etsi_its_srem_ts_coding/srem_DSRC_ThrottleConfidence.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_DSRC_SpeedandHeadingandThrottleConfidence */
typedef struct srem_DSRC_SpeedandHeadingandThrottleConfidence {
	srem_DSRC_HeadingConfidenceDSRC_t	 heading;
	srem_DSRC_SpeedConfidenceDSRC_t	 speed;
	srem_DSRC_ThrottleConfidence_t	 throttle;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_DSRC_SpeedandHeadingandThrottleConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_DSRC_SpeedandHeadingandThrottleConfidence;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_DSRC_SpeedandHeadingandThrottleConfidence_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_DSRC_SpeedandHeadingandThrottleConfidence_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _srem_DSRC_SpeedandHeadingandThrottleConfidence_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
