/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_DangerousGoodsExtended_H_
#define	_srem_ETSI_ITS_CDD_DangerousGoodsExtended_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_DangerousGoodsBasic.h"
#include <etsi_its_srem_ts_coding/NativeInteger.h>
#include <etsi_its_srem_ts_coding/BOOLEAN.h>
#include <etsi_its_srem_ts_coding/IA5String.h>
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_PhoneNumber.h"
#include <etsi_its_srem_ts_coding/UTF8String.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ETSI-ITS-CDD_DangerousGoodsExtended */
typedef struct srem_ETSI_ITS_CDD_DangerousGoodsExtended {
	srem_ETSI_ITS_CDD_DangerousGoodsBasic_t	 dangerousGoodsType;
	long	 unNumber;
	BOOLEAN_t	 elevatedTemperature;
	BOOLEAN_t	 tunnelsRestricted;
	BOOLEAN_t	 limitedQuantity;
	IA5String_t	*emergencyActionCode;	/* OPTIONAL */
	srem_ETSI_ITS_CDD_PhoneNumber_t	*phoneNumber;	/* OPTIONAL */
	UTF8String_t	*companyName;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ETSI_ITS_CDD_DangerousGoodsExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_DangerousGoodsExtended;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_DangerousGoodsExtended_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
