/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_DSRC_TransitVehicleOccupancy_H_
#define	_srem_DSRC_TransitVehicleOccupancy_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_DSRC_TransitVehicleOccupancy {
	srem_DSRC_TransitVehicleOccupancy_occupancyUnknown	= 0,
	srem_DSRC_TransitVehicleOccupancy_occupancyEmpty	= 1,
	srem_DSRC_TransitVehicleOccupancy_occupancyVeryLow	= 2,
	srem_DSRC_TransitVehicleOccupancy_occupancyLow	= 3,
	srem_DSRC_TransitVehicleOccupancy_occupancyMed	= 4,
	srem_DSRC_TransitVehicleOccupancy_occupancyHigh	= 5,
	srem_DSRC_TransitVehicleOccupancy_occupancyNearlyFull	= 6,
	srem_DSRC_TransitVehicleOccupancy_occupancyFull	= 7
} e_srem_DSRC_TransitVehicleOccupancy;

/* srem_DSRC_TransitVehicleOccupancy */
typedef long	 srem_DSRC_TransitVehicleOccupancy_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_DSRC_TransitVehicleOccupancy_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_DSRC_TransitVehicleOccupancy;
extern const asn_INTEGER_specifics_t asn_SPC_srem_DSRC_TransitVehicleOccupancy_specs_1;
asn_struct_free_f srem_DSRC_TransitVehicleOccupancy_free;
asn_struct_print_f srem_DSRC_TransitVehicleOccupancy_print;
asn_constr_check_f srem_DSRC_TransitVehicleOccupancy_constraint;
jer_type_encoder_f srem_DSRC_TransitVehicleOccupancy_encode_jer;
per_type_decoder_f srem_DSRC_TransitVehicleOccupancy_decode_uper;
per_type_encoder_f srem_DSRC_TransitVehicleOccupancy_encode_uper;
per_type_decoder_f srem_DSRC_TransitVehicleOccupancy_decode_aper;
per_type_encoder_f srem_DSRC_TransitVehicleOccupancy_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_DSRC_TransitVehicleOccupancy_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
