/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ReferencePositionWithConfidence_H_
#define	_srem_ReferencePositionWithConfidence_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_Latitude.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_Longitude.h"
#include "etsi_its_srem_ts_coding/srem_PositionConfidenceEllipse.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_Altitude.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ReferencePositionWithConfidence */
typedef struct srem_ReferencePositionWithConfidence {
	srem_ETSI_ITS_CDD_Latitude_t	 latitude;
	srem_ETSI_ITS_CDD_Longitude_t	 longitude;
	srem_PositionConfidenceEllipse_t	 positionConfidenceEllipse;
	srem_ETSI_ITS_CDD_Altitude_t	 altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ReferencePositionWithConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ReferencePositionWithConfidence;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ReferencePositionWithConfidence_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ReferencePositionWithConfidence_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ReferencePositionWithConfidence_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
