/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_MultiplicativeFactor_H_
#define	_srem_MultiplicativeFactor_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_MultiplicativeFactor {
	srem_MultiplicativeFactor_tenth	= 0,
	srem_MultiplicativeFactor_half	= 1,
	srem_MultiplicativeFactor_two	= 2,
	srem_MultiplicativeFactor_three	= 3,
	srem_MultiplicativeFactor_five	= 4,
	srem_MultiplicativeFactor_ten	= 5,
	srem_MultiplicativeFactor_fifty	= 6,
	srem_MultiplicativeFactor_hundred	= 7
	/*
	 * Enumeration is extensible
	 */
} e_srem_MultiplicativeFactor;

/* srem_MultiplicativeFactor */
typedef long	 srem_MultiplicativeFactor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_MultiplicativeFactor;
asn_struct_free_f srem_MultiplicativeFactor_free;
asn_struct_print_f srem_MultiplicativeFactor_print;
asn_constr_check_f srem_MultiplicativeFactor_constraint;
jer_type_encoder_f srem_MultiplicativeFactor_encode_jer;
per_type_decoder_f srem_MultiplicativeFactor_decode_uper;
per_type_encoder_f srem_MultiplicativeFactor_encode_uper;
per_type_decoder_f srem_MultiplicativeFactor_decode_aper;
per_type_encoder_f srem_MultiplicativeFactor_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_MultiplicativeFactor_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
