/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_LongitudinalAcceleration_H_
#define	_srem_ts_LongitudinalAcceleration_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ts_LongitudinalAccelerationValue.h"
#include "etsi_its_srem_ts_coding/srem_ts_AccelerationConfidence.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ts_LongitudinalAcceleration */
typedef struct srem_ts_LongitudinalAcceleration {
	srem_ts_LongitudinalAccelerationValue_t	 longitudinalAccelerationValue;
	srem_ts_AccelerationConfidence_t	 longitudinalAccelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_LongitudinalAcceleration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_LongitudinalAcceleration;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_LongitudinalAcceleration_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
