/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_DSRC_FullPositionVector_H_
#define	_srem_ETSI_ITS_DSRC_FullPositionVector_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_Longitude.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_Latitude.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_Elevation.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_HeadingDSRC.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_TimeConfidence.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_DDateTime;
struct srem_TransmissionAndSpeed;
struct srem_PositionalAccuracy;
struct srem_PositionConfidenceSet;
struct srem_SpeedandHeadingandThrottleConfidence;

/* srem_ETSI-ITS-DSRC_FullPositionVector */
typedef struct srem_ETSI_ITS_DSRC_FullPositionVector {
	struct srem_DDateTime	*utcTime;	/* OPTIONAL */
	srem_ETSI_ITS_CDD_Longitude_t	 Long;
	srem_ETSI_ITS_CDD_Latitude_t	 lat;
	srem_ETSI_ITS_DSRC_Elevation_t	*elevation;	/* OPTIONAL */
	srem_ETSI_ITS_DSRC_HeadingDSRC_t	*heading;	/* OPTIONAL */
	struct srem_TransmissionAndSpeed	*speed;	/* OPTIONAL */
	struct srem_PositionalAccuracy	*posAccuracy;	/* OPTIONAL */
	srem_ETSI_ITS_DSRC_TimeConfidence_t	*timeConfidence;	/* OPTIONAL */
	struct srem_PositionConfidenceSet	*posConfidence;	/* OPTIONAL */
	struct srem_SpeedandHeadingandThrottleConfidence	*speedConfidence;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ETSI_ITS_DSRC_FullPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_DSRC_FullPositionVector;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ETSI_ITS_DSRC_FullPositionVector_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ETSI_ITS_DSRC_FullPositionVector_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_DDateTime.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_TransmissionAndSpeed.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_PositionalAccuracy.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_PositionConfidenceSet.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_SpeedandHeadingandThrottleConfidence.h"

#endif	/* _srem_ETSI_ITS_DSRC_FullPositionVector_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
