/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_DSRC_SignalRequest_H_
#define	_srem_ETSI_ITS_DSRC_SignalRequest_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_IntersectionReferenceID.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_RequestID.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_PriorityRequestType.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_IntersectionAccessPoint.h"
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_IntersectionAccessPoint;
struct srem_Reg_SignalRequest;

/* srem_ETSI-ITS-DSRC_SignalRequest */
typedef struct srem_ETSI_ITS_DSRC_SignalRequest {
	srem_ETSI_ITS_DSRC_IntersectionReferenceID_t	 id;
	srem_ETSI_ITS_DSRC_RequestID_t	 requestID;
	srem_ETSI_ITS_DSRC_PriorityRequestType_t	 requestType;
	srem_ETSI_ITS_DSRC_IntersectionAccessPoint_t	 inBoundLane;
	struct srem_IntersectionAccessPoint	*outBoundLane;	/* OPTIONAL */
	struct srem_ETSI_ITS_DSRC_SignalRequest__regional {
		A_SEQUENCE_OF(struct srem_Reg_SignalRequest) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ETSI_ITS_DSRC_SignalRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_DSRC_SignalRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ETSI_ITS_DSRC_SignalRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ETSI_ITS_DSRC_SignalRequest_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_IntersectionAccessPoint.h"
#include "etsi_its_srem_ts_coding/srem_RegionalExtension.h"

#endif	/* _srem_ETSI_ITS_DSRC_SignalRequest_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
