/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_EuVehicleCategoryL_H_
#define	_srem_EuVehicleCategoryL_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_EuVehicleCategoryL {
	srem_EuVehicleCategoryL_l1	= 0,
	srem_EuVehicleCategoryL_l2	= 1,
	srem_EuVehicleCategoryL_l3	= 2,
	srem_EuVehicleCategoryL_l4	= 3,
	srem_EuVehicleCategoryL_l5	= 4,
	srem_EuVehicleCategoryL_l6	= 5,
	srem_EuVehicleCategoryL_l7	= 6
} e_srem_EuVehicleCategoryL;

/* srem_EuVehicleCategoryL */
typedef long	 srem_EuVehicleCategoryL_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_EuVehicleCategoryL_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_EuVehicleCategoryL;
extern const asn_INTEGER_specifics_t asn_SPC_srem_EuVehicleCategoryL_specs_1;
asn_struct_free_f srem_EuVehicleCategoryL_free;
asn_struct_print_f srem_EuVehicleCategoryL_print;
asn_constr_check_f srem_EuVehicleCategoryL_constraint;
jer_type_encoder_f srem_EuVehicleCategoryL_encode_jer;
per_type_decoder_f srem_EuVehicleCategoryL_decode_uper;
per_type_encoder_f srem_EuVehicleCategoryL_encode_uper;
per_type_decoder_f srem_EuVehicleCategoryL_decode_aper;
per_type_encoder_f srem_EuVehicleCategoryL_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_EuVehicleCategoryL_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
