/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_InterferenceManagementZoneType_H_
#define	_srem_InterferenceManagementZoneType_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_InterferenceManagementZoneType {
	srem_InterferenceManagementZoneType_permanentCenDsrcTolling	= 0,
	srem_InterferenceManagementZoneType_temporaryCenDsrcTolling	= 1,
	srem_InterferenceManagementZoneType_unavailable	= 2,
	srem_InterferenceManagementZoneType_urbanRail	= 3,
	srem_InterferenceManagementZoneType_satelliteStation	= 4,
	srem_InterferenceManagementZoneType_fixedLinks	= 5
	/*
	 * Enumeration is extensible
	 */
} e_srem_InterferenceManagementZoneType;

/* srem_InterferenceManagementZoneType */
typedef long	 srem_InterferenceManagementZoneType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_InterferenceManagementZoneType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_InterferenceManagementZoneType;
extern const asn_INTEGER_specifics_t asn_SPC_srem_InterferenceManagementZoneType_specs_1;
asn_struct_free_f srem_InterferenceManagementZoneType_free;
asn_struct_print_f srem_InterferenceManagementZoneType_print;
asn_constr_check_f srem_InterferenceManagementZoneType_constraint;
jer_type_encoder_f srem_InterferenceManagementZoneType_encode_jer;
per_type_decoder_f srem_InterferenceManagementZoneType_decode_uper;
per_type_encoder_f srem_InterferenceManagementZoneType_encode_uper;
per_type_decoder_f srem_InterferenceManagementZoneType_decode_aper;
per_type_encoder_f srem_InterferenceManagementZoneType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_InterferenceManagementZoneType_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
