/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_DSRC_RestrictionClassAssignment_H_
#define	_srem_ETSI_ITS_DSRC_RestrictionClassAssignment_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_RestrictionClassID.h"
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-DSRC_RestrictionUserTypeList.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ETSI-ITS-DSRC_RestrictionClassAssignment */
typedef struct srem_ETSI_ITS_DSRC_RestrictionClassAssignment {
	srem_ETSI_ITS_DSRC_RestrictionClassID_t	 id;
	srem_ETSI_ITS_DSRC_RestrictionUserTypeList_t	 users;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ETSI_ITS_DSRC_RestrictionClassAssignment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_DSRC_RestrictionClassAssignment;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ETSI_ITS_DSRC_RestrictionClassAssignment_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ETSI_ITS_DSRC_RestrictionClassAssignment_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_DSRC_RestrictionClassAssignment_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
