/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ITS_Container_CenDsrcTollingZone_H_
#define	_srem_ITS_Container_CenDsrcTollingZone_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ITS-Container_Latitude.h"
#include "etsi_its_srem_ts_coding/srem_ITS-Container_Longitude.h"
#include "etsi_its_srem_ts_coding/srem_ITS-Container_CenDsrcTollingZoneID.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ITS-Container_CenDsrcTollingZone */
typedef struct srem_ITS_Container_CenDsrcTollingZone {
	srem_ITS_Container_Latitude_t	 protectedZoneLatitude;
	srem_ITS_Container_Longitude_t	 protectedZoneLongitude;
	srem_ITS_Container_CenDsrcTollingZoneID_t	*cenDsrcTollingZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ITS_Container_CenDsrcTollingZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ITS_Container_CenDsrcTollingZone;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ITS_Container_CenDsrcTollingZone_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
