/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_LaneSharing_H_
#define	_srem_ts_LaneSharing_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ts_LaneSharing {
	srem_ts_LaneSharing_overlappingLaneDescriptionProvided	= 0,
	srem_ts_LaneSharing_multipleLanesTreatedAsOneLane	= 1,
	srem_ts_LaneSharing_otherNonMotorizedTrafficTypes	= 2,
	srem_ts_LaneSharing_individualMotorizedVehicleTraffic	= 3,
	srem_ts_LaneSharing_busVehicleTraffic	= 4,
	srem_ts_LaneSharing_taxiVehicleTraffic	= 5,
	srem_ts_LaneSharing_pedestriansTraffic	= 6,
	srem_ts_LaneSharing_cyclistVehicleTraffic	= 7,
	srem_ts_LaneSharing_trackedVehicleTraffic	= 8,
	srem_ts_LaneSharing_pedestrianTraffic	= 9
} e_srem_ts_LaneSharing;

/* srem_ts_LaneSharing */
typedef BIT_STRING_t	 srem_ts_LaneSharing_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ts_LaneSharing_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_LaneSharing;
asn_struct_free_f srem_ts_LaneSharing_free;
asn_struct_print_f srem_ts_LaneSharing_print;
asn_constr_check_f srem_ts_LaneSharing_constraint;
jer_type_encoder_f srem_ts_LaneSharing_encode_jer;
per_type_decoder_f srem_ts_LaneSharing_decode_uper;
per_type_encoder_f srem_ts_LaneSharing_encode_uper;
per_type_decoder_f srem_ts_LaneSharing_decode_aper;
per_type_encoder_f srem_ts_LaneSharing_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_LaneSharing_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
