/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_GeneralizedLanePositions_H_
#define	_srem_GeneralizedLanePositions_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_GeneralizedLanePosition;

/* srem_GeneralizedLanePositions */
typedef struct srem_GeneralizedLanePositions {
	A_SEQUENCE_OF(struct srem_GeneralizedLanePosition) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_GeneralizedLanePositions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_GeneralizedLanePositions;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_GeneralizedLanePosition.h"

#endif	/* _srem_GeneralizedLanePositions_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
