/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ITS_Container_Longitude_H_
#define	_srem_ITS_Container_Longitude_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ITS_Container_Longitude {
	srem_ITS_Container_Longitude_oneMicrodegreeEast	= 10,
	srem_ITS_Container_Longitude_oneMicrodegreeWest	= -10,
	srem_ITS_Container_Longitude_unavailable	= 1800000001
} e_srem_ITS_Container_Longitude;

/* srem_ITS-Container_Longitude */
typedef long	 srem_ITS_Container_Longitude_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ITS_Container_Longitude_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ITS_Container_Longitude;
asn_struct_free_f srem_ITS_Container_Longitude_free;
asn_struct_print_f srem_ITS_Container_Longitude_print;
asn_constr_check_f srem_ITS_Container_Longitude_constraint;
jer_type_encoder_f srem_ITS_Container_Longitude_encode_jer;
per_type_decoder_f srem_ITS_Container_Longitude_decode_uper;
per_type_encoder_f srem_ITS_Container_Longitude_encode_uper;
per_type_decoder_f srem_ITS_Container_Longitude_decode_aper;
per_type_encoder_f srem_ITS_Container_Longitude_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ITS_Container_Longitude_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
