/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_DeltaPositions_H_
#define	_srem_DeltaPositions_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_DeltaPosition;

/* srem_DeltaPositions */
typedef struct srem_DeltaPositions {
	A_SEQUENCE_OF(struct srem_DeltaPosition) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_DeltaPositions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_DeltaPositions;
extern asn_SET_OF_specifics_t asn_SPC_srem_DeltaPositions_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_DeltaPositions_1[1];
extern asn_per_constraints_t asn_PER_type_srem_DeltaPositions_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_DeltaPosition.h"

#endif	/* _srem_DeltaPositions_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
