/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_VehicleIdentification_H_
#define	_srem_ts_VehicleIdentification_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ts_WMInumber.h"
#include "etsi_its_srem_ts_coding/srem_ts_VDS.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ts_VehicleIdentification */
typedef struct srem_ts_VehicleIdentification {
	srem_ts_WMInumber_t	*wMInumber;	/* OPTIONAL */
	srem_ts_VDS_t	*vDS;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_VehicleIdentification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_VehicleIdentification;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_VehicleIdentification_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
