/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_MapData_H_
#define	_srem_ts_MapData_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ts_MinuteOfTheYear.h"
#include "etsi_its_srem_ts_coding/srem_ts_MsgCount.h"
#include "etsi_its_srem_ts_coding/srem_ts_LayerType.h"
#include "etsi_its_srem_ts_coding/srem_ts_LayerID.h"
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_ts_IntersectionGeometryList;
struct srem_ts_RoadSegmentList;
struct srem_ts_DataParameters;
struct srem_ts_RestrictionClassList;
struct srem_ts_Reg_MapData;

/* srem_ts_MapData */
typedef struct srem_ts_MapData {
	srem_ts_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	srem_ts_MsgCount_t	 msgIssueRevision;
	srem_ts_LayerType_t	*layerType;	/* OPTIONAL */
	srem_ts_LayerID_t	*layerID;	/* OPTIONAL */
	struct srem_ts_IntersectionGeometryList	*intersections;	/* OPTIONAL */
	struct srem_ts_RoadSegmentList	*roadSegments;	/* OPTIONAL */
	struct srem_ts_DataParameters	*dataParameters;	/* OPTIONAL */
	struct srem_ts_RestrictionClassList	*restrictionList;	/* OPTIONAL */
	struct srem_ts_MapData__regional {
		A_SEQUENCE_OF(struct srem_ts_Reg_MapData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_MapData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_MapData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ts_IntersectionGeometryList.h"
#include "etsi_its_srem_ts_coding/srem_ts_RoadSegmentList.h"
#include "etsi_its_srem_ts_coding/srem_ts_DataParameters.h"
#include "etsi_its_srem_ts_coding/srem_ts_RestrictionClassList.h"
#include "etsi_its_srem_ts_coding/srem_ts_RegionalExtension.h"

#endif	/* _srem_ts_MapData_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
