/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_SignalStatusMessage_H_
#define	_srem_ts_SignalStatusMessage_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ts_MinuteOfTheYear.h"
#include "etsi_its_srem_ts_coding/srem_ts_DSecond.h"
#include "etsi_its_srem_ts_coding/srem_ts_MsgCount.h"
#include "etsi_its_srem_ts_coding/srem_ts_SignalStatusList.h"
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_ts_Reg_SignalStatusMessage;

/* srem_ts_SignalStatusMessage */
typedef struct srem_ts_SignalStatusMessage {
	srem_ts_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	srem_ts_DSecond_t	 second;
	srem_ts_MsgCount_t	*sequenceNumber;	/* OPTIONAL */
	srem_ts_SignalStatusList_t	 status;
	struct srem_ts_SignalStatusMessage__regional {
		A_SEQUENCE_OF(struct srem_ts_Reg_SignalStatusMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_SignalStatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_SignalStatusMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ts_RegionalExtension.h"

#endif	/* _srem_ts_SignalStatusMessage_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
