/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVIAEINumberingAndDataStructures"
 * 	found in "/input/ISO14816_AVIAEINumberingAndDataStructures.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_CS8_H_
#define	_srem_ts_CS8_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/BIT_STRING.h>
#include "etsi_its_srem_ts_coding/srem_ts_CountryCode.h"
#include "etsi_its_srem_ts_coding/srem_ts_TaxCode.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ts_CS8 */
typedef struct srem_ts_CS8 {
	BIT_STRING_t	 fill;
	srem_ts_CountryCode_t	 countryCode;
	srem_ts_TaxCode_t	 taxCode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_CS8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_CS8;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_CS8_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
