/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_SensorType_H_
#define	_srem_SensorType_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_SensorType {
	srem_SensorType_undefined	= 0,
	srem_SensorType_radar	= 1,
	srem_SensorType_lidar	= 2,
	srem_SensorType_monovideo	= 3,
	srem_SensorType_stereovision	= 4,
	srem_SensorType_nightvision	= 5,
	srem_SensorType_ultrasonic	= 6,
	srem_SensorType_pmd	= 7,
	srem_SensorType_inductionLoop	= 8,
	srem_SensorType_sphericalCamera	= 9,
	srem_SensorType_uwb	= 10,
	srem_SensorType_acoustic	= 11,
	srem_SensorType_localAggregation	= 12,
	srem_SensorType_itsAggregation	= 13,
	srem_SensorType_rfid	= 14
} e_srem_SensorType;

/* srem_SensorType */
typedef long	 srem_SensorType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_SensorType;
asn_struct_free_f srem_SensorType_free;
asn_struct_print_f srem_SensorType_print;
asn_constr_check_f srem_SensorType_constraint;
jer_type_encoder_f srem_SensorType_encode_jer;
per_type_decoder_f srem_SensorType_decode_uper;
per_type_encoder_f srem_SensorType_encode_uper;
per_type_decoder_f srem_SensorType_decode_aper;
per_type_encoder_f srem_SensorType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_SensorType_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
