/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ParkingSpaceStatus_H_
#define	_srem_ParkingSpaceStatus_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NULL.h>
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_TimestampIts.h"
#include <etsi_its_srem_ts_coding/NativeInteger.h>
#include <etsi_its_srem_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ParkingSpaceStatus_PR {
	srem_ParkingSpaceStatus_PR_NOTHING,	/* No components present */
	srem_ParkingSpaceStatus_PR_unknown,
	srem_ParkingSpaceStatus_PR_free,
	srem_ParkingSpaceStatus_PR_freeUntil,
	srem_ParkingSpaceStatus_PR_fullyOccupied,
	srem_ParkingSpaceStatus_PR_partiallyOccupied,
	srem_ParkingSpaceStatus_PR_occupiedUntil,
	srem_ParkingSpaceStatus_PR_reservedUntil,
	srem_ParkingSpaceStatus_PR_accessBlocked,
	srem_ParkingSpaceStatus_PR_retrictedUsage
	/* Extensions may appear below */
	
} srem_ParkingSpaceStatus_PR;

/* srem_ParkingSpaceStatus */
typedef struct srem_ParkingSpaceStatus {
	srem_ParkingSpaceStatus_PR present;
	union srem_ParkingSpaceStatus_u {
		NULL_t	 unknown;
		NULL_t	 free;
		srem_ETSI_ITS_CDD_TimestampIts_t	 freeUntil;
		NULL_t	 fullyOccupied;
		long	 partiallyOccupied;
		srem_ETSI_ITS_CDD_TimestampIts_t	 occupiedUntil;
		srem_ETSI_ITS_CDD_TimestampIts_t	 reservedUntil;
		NULL_t	 accessBlocked;
		NULL_t	 retrictedUsage;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ParkingSpaceStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ParkingSpaceStatus;
extern asn_CHOICE_specifics_t asn_SPC_srem_ParkingSpaceStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ParkingSpaceStatus_1[9];
extern asn_per_constraints_t asn_PER_type_srem_ParkingSpaceStatus_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ParkingSpaceStatus_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
