/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_PositionOfOccupants_H_
#define	_srem_ts_PositionOfOccupants_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ts_PositionOfOccupants {
	srem_ts_PositionOfOccupants_row1LeftOccupied	= 0,
	srem_ts_PositionOfOccupants_row1RightOccupied	= 1,
	srem_ts_PositionOfOccupants_row1MidOccupied	= 2,
	srem_ts_PositionOfOccupants_row1NotDetectable	= 3,
	srem_ts_PositionOfOccupants_row1NotPresent	= 4,
	srem_ts_PositionOfOccupants_row2LeftOccupied	= 5,
	srem_ts_PositionOfOccupants_row2RightOccupied	= 6,
	srem_ts_PositionOfOccupants_row2MidOccupied	= 7,
	srem_ts_PositionOfOccupants_row2NotDetectable	= 8,
	srem_ts_PositionOfOccupants_row2NotPresent	= 9,
	srem_ts_PositionOfOccupants_row3LeftOccupied	= 10,
	srem_ts_PositionOfOccupants_row3RightOccupied	= 11,
	srem_ts_PositionOfOccupants_row3MidOccupied	= 12,
	srem_ts_PositionOfOccupants_row3NotDetectable	= 13,
	srem_ts_PositionOfOccupants_row3NotPresent	= 14,
	srem_ts_PositionOfOccupants_row4LeftOccupied	= 15,
	srem_ts_PositionOfOccupants_row4RightOccupied	= 16,
	srem_ts_PositionOfOccupants_row4MidOccupied	= 17,
	srem_ts_PositionOfOccupants_row4NotDetectable	= 18,
	srem_ts_PositionOfOccupants_row4NotPresent	= 19
} e_srem_ts_PositionOfOccupants;

/* srem_ts_PositionOfOccupants */
typedef BIT_STRING_t	 srem_ts_PositionOfOccupants_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_PositionOfOccupants;
asn_struct_free_f srem_ts_PositionOfOccupants_free;
asn_struct_print_f srem_ts_PositionOfOccupants_print;
asn_constr_check_f srem_ts_PositionOfOccupants_constraint;
jer_type_encoder_f srem_ts_PositionOfOccupants_encode_jer;
per_type_decoder_f srem_ts_PositionOfOccupants_decode_uper;
per_type_encoder_f srem_ts_PositionOfOccupants_encode_uper;
per_type_decoder_f srem_ts_PositionOfOccupants_decode_aper;
per_type_encoder_f srem_ts_PositionOfOccupants_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_PositionOfOccupants_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
