/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_VelocityPolarWithZ_H_
#define	_srem_VelocityPolarWithZ_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_Speed.h"
#include "etsi_its_srem_ts_coding/srem_CartesianAngle.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_VelocityComponent;

/* srem_VelocityPolarWithZ */
typedef struct srem_VelocityPolarWithZ {
	srem_ETSI_ITS_CDD_Speed_t	 velocityMagnitude;
	srem_CartesianAngle_t	 velocityDirection;
	struct srem_VelocityComponent	*zVelocity;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_VelocityPolarWithZ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_VelocityPolarWithZ;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_VelocityPolarWithZ_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_VelocityPolarWithZ_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_VelocityComponent.h"

#endif	/* _srem_VelocityPolarWithZ_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
