/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_CauseCodeType_H_
#define	_srem_ETSI_ITS_CDD_CauseCodeType_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ETSI_ITS_CDD_CauseCodeType {
	srem_ETSI_ITS_CDD_CauseCodeType_trafficCondition	= 1,
	srem_ETSI_ITS_CDD_CauseCodeType_accident	= 2,
	srem_ETSI_ITS_CDD_CauseCodeType_roadworks	= 3,
	srem_ETSI_ITS_CDD_CauseCodeType_detectedRoadworks	= 4,
	srem_ETSI_ITS_CDD_CauseCodeType_impassability	= 5,
	srem_ETSI_ITS_CDD_CauseCodeType_adhesion	= 6,
	srem_ETSI_ITS_CDD_CauseCodeType_aquaplaning	= 7,
	srem_ETSI_ITS_CDD_CauseCodeType_hazardousLocation_SurfaceCondition	= 9,
	srem_ETSI_ITS_CDD_CauseCodeType_hazardousLocation_ObstacleOnTheRoad	= 10,
	srem_ETSI_ITS_CDD_CauseCodeType_hazardousLocation_AnimalOnTheRoad	= 11,
	srem_ETSI_ITS_CDD_CauseCodeType_humanPresenceOnTheRoad	= 12,
	srem_ETSI_ITS_CDD_CauseCodeType_wrongWayDriving	= 14,
	srem_ETSI_ITS_CDD_CauseCodeType_rescueRecoveryAndMaintenanceWorkInProgress	= 15,
	srem_ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_ExtremeWeatherCondition	= 17,
	srem_ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_Visibility	= 18,
	srem_ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_Precipitation	= 19,
	srem_ETSI_ITS_CDD_CauseCodeType_violence	= 20,
	srem_ETSI_ITS_CDD_CauseCodeType_slowVehicle	= 26,
	srem_ETSI_ITS_CDD_CauseCodeType_dangerousEndOfQueue	= 27,
	srem_ETSI_ITS_CDD_CauseCodeType_publicTransportVehicleApproaching	= 28,
	srem_ETSI_ITS_CDD_CauseCodeType_vehicleBreakdown	= 91,
	srem_ETSI_ITS_CDD_CauseCodeType_postCrash	= 92,
	srem_ETSI_ITS_CDD_CauseCodeType_humanProblem	= 93,
	srem_ETSI_ITS_CDD_CauseCodeType_stationaryVehicle	= 94,
	srem_ETSI_ITS_CDD_CauseCodeType_emergencyVehicleApproaching	= 95,
	srem_ETSI_ITS_CDD_CauseCodeType_hazardousLocation_DangerousCurve	= 96,
	srem_ETSI_ITS_CDD_CauseCodeType_collisionRisk	= 97,
	srem_ETSI_ITS_CDD_CauseCodeType_signalViolation	= 98,
	srem_ETSI_ITS_CDD_CauseCodeType_dangerousSituation	= 99,
	srem_ETSI_ITS_CDD_CauseCodeType_railwayLevelCrossing	= 100
} e_srem_ETSI_ITS_CDD_CauseCodeType;

/* srem_ETSI-ITS-CDD_CauseCodeType */
typedef long	 srem_ETSI_ITS_CDD_CauseCodeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ETSI_ITS_CDD_CauseCodeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_CauseCodeType;
asn_struct_free_f srem_ETSI_ITS_CDD_CauseCodeType_free;
asn_struct_print_f srem_ETSI_ITS_CDD_CauseCodeType_print;
asn_constr_check_f srem_ETSI_ITS_CDD_CauseCodeType_constraint;
jer_type_encoder_f srem_ETSI_ITS_CDD_CauseCodeType_encode_jer;
per_type_decoder_f srem_ETSI_ITS_CDD_CauseCodeType_decode_uper;
per_type_encoder_f srem_ETSI_ITS_CDD_CauseCodeType_encode_uper;
per_type_decoder_f srem_ETSI_ITS_CDD_CauseCodeType_decode_aper;
per_type_encoder_f srem_ETSI_ITS_CDD_CauseCodeType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_CauseCodeType_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
