/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ITS_Container_SpecialTransportType_H_
#define	_srem_ITS_Container_SpecialTransportType_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ITS_Container_SpecialTransportType {
	srem_ITS_Container_SpecialTransportType_heavyLoad	= 0,
	srem_ITS_Container_SpecialTransportType_excessWidth	= 1,
	srem_ITS_Container_SpecialTransportType_excessLength	= 2,
	srem_ITS_Container_SpecialTransportType_excessHeight	= 3
} e_srem_ITS_Container_SpecialTransportType;

/* srem_ITS-Container_SpecialTransportType */
typedef BIT_STRING_t	 srem_ITS_Container_SpecialTransportType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ITS_Container_SpecialTransportType;
asn_struct_free_f srem_ITS_Container_SpecialTransportType_free;
asn_struct_print_f srem_ITS_Container_SpecialTransportType_print;
asn_constr_check_f srem_ITS_Container_SpecialTransportType_constraint;
jer_type_encoder_f srem_ITS_Container_SpecialTransportType_encode_jer;
per_type_decoder_f srem_ITS_Container_SpecialTransportType_decode_uper;
per_type_encoder_f srem_ITS_Container_SpecialTransportType_encode_uper;
per_type_decoder_f srem_ITS_Container_SpecialTransportType_decode_aper;
per_type_encoder_f srem_ITS_Container_SpecialTransportType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ITS_Container_SpecialTransportType_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
