/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_MessageSegmentationInfo_H_
#define	_srem_MessageSegmentationInfo_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_CardinalNumber3b.h"
#include "etsi_its_srem_ts_coding/srem_OrdinalNumber3b.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_MessageSegmentationInfo */
typedef struct srem_MessageSegmentationInfo {
	srem_CardinalNumber3b_t	 totalMsgNo;
	srem_OrdinalNumber3b_t	 thisMsgNo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_MessageSegmentationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_MessageSegmentationInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_MessageSegmentationInfo_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
