/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_YawRateConfidence_H_
#define	_srem_ETSI_ITS_CDD_YawRateConfidence_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ETSI_ITS_CDD_YawRateConfidence {
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_000_01	= 0,
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_000_05	= 1,
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_000_10	= 2,
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_001_00	= 3,
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_005_00	= 4,
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_010_00	= 5,
	srem_ETSI_ITS_CDD_YawRateConfidence_degSec_100_00	= 6,
	srem_ETSI_ITS_CDD_YawRateConfidence_outOfRange	= 7,
	srem_ETSI_ITS_CDD_YawRateConfidence_unavailable	= 8
} e_srem_ETSI_ITS_CDD_YawRateConfidence;

/* srem_ETSI-ITS-CDD_YawRateConfidence */
typedef long	 srem_ETSI_ITS_CDD_YawRateConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_ETSI_ITS_CDD_YawRateConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_YawRateConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_srem_ETSI_ITS_CDD_YawRateConfidence_specs_1;
asn_struct_free_f srem_ETSI_ITS_CDD_YawRateConfidence_free;
asn_struct_print_f srem_ETSI_ITS_CDD_YawRateConfidence_print;
asn_constr_check_f srem_ETSI_ITS_CDD_YawRateConfidence_constraint;
jer_type_encoder_f srem_ETSI_ITS_CDD_YawRateConfidence_encode_jer;
per_type_decoder_f srem_ETSI_ITS_CDD_YawRateConfidence_decode_uper;
per_type_encoder_f srem_ETSI_ITS_CDD_YawRateConfidence_encode_uper;
per_type_decoder_f srem_ETSI_ITS_CDD_YawRateConfidence_decode_aper;
per_type_encoder_f srem_ETSI_ITS_CDD_YawRateConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_YawRateConfidence_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
