/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_DeltaTimeQuarterSecond_H_
#define	_srem_DeltaTimeQuarterSecond_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_DeltaTimeQuarterSecond {
	srem_DeltaTimeQuarterSecond_unavailable	= 255
} e_srem_DeltaTimeQuarterSecond;

/* srem_DeltaTimeQuarterSecond */
typedef long	 srem_DeltaTimeQuarterSecond_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_DeltaTimeQuarterSecond_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_DeltaTimeQuarterSecond;
asn_struct_free_f srem_DeltaTimeQuarterSecond_free;
asn_struct_print_f srem_DeltaTimeQuarterSecond_print;
asn_constr_check_f srem_DeltaTimeQuarterSecond_constraint;
jer_type_encoder_f srem_DeltaTimeQuarterSecond_encode_jer;
per_type_decoder_f srem_DeltaTimeQuarterSecond_decode_uper;
per_type_encoder_f srem_DeltaTimeQuarterSecond_encode_uper;
per_type_decoder_f srem_DeltaTimeQuarterSecond_decode_aper;
per_type_encoder_f srem_DeltaTimeQuarterSecond_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_DeltaTimeQuarterSecond_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
