/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_CartesianAngleValue_H_
#define	_srem_CartesianAngleValue_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_CartesianAngleValue {
	srem_CartesianAngleValue_valueNotUsed	= 3600,
	srem_CartesianAngleValue_unavailable	= 3601
} e_srem_CartesianAngleValue;

/* srem_CartesianAngleValue */
typedef long	 srem_CartesianAngleValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_srem_CartesianAngleValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_srem_CartesianAngleValue;
asn_struct_free_f srem_CartesianAngleValue_free;
asn_struct_print_f srem_CartesianAngleValue_print;
asn_constr_check_f srem_CartesianAngleValue_constraint;
jer_type_encoder_f srem_CartesianAngleValue_encode_jer;
per_type_decoder_f srem_CartesianAngleValue_decode_uper;
per_type_encoder_f srem_CartesianAngleValue_encode_uper;
per_type_decoder_f srem_CartesianAngleValue_decode_aper;
per_type_encoder_f srem_CartesianAngleValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_CartesianAngleValue_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
