/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ETSI_ITS_CDD_TrafficRule_H_
#define	_srem_ETSI_ITS_CDD_TrafficRule_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ETSI_ITS_CDD_TrafficRule {
	srem_ETSI_ITS_CDD_TrafficRule_noPassing	= 0,
	srem_ETSI_ITS_CDD_TrafficRule_noPassingForTrucks	= 1,
	srem_ETSI_ITS_CDD_TrafficRule_passToRight	= 2,
	srem_ETSI_ITS_CDD_TrafficRule_passToLeft	= 3,
	/*
	 * Enumeration is extensible
	 */
	srem_ETSI_ITS_CDD_TrafficRule_passToLeftOrRight	= 4
} e_srem_ETSI_ITS_CDD_TrafficRule;

/* srem_ETSI-ITS-CDD_TrafficRule */
typedef long	 srem_ETSI_ITS_CDD_TrafficRule_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ETSI_ITS_CDD_TrafficRule;
asn_struct_free_f srem_ETSI_ITS_CDD_TrafficRule_free;
asn_struct_print_f srem_ETSI_ITS_CDD_TrafficRule_print;
asn_constr_check_f srem_ETSI_ITS_CDD_TrafficRule_constraint;
jer_type_encoder_f srem_ETSI_ITS_CDD_TrafficRule_encode_jer;
per_type_decoder_f srem_ETSI_ITS_CDD_TrafficRule_decode_uper;
per_type_encoder_f srem_ETSI_ITS_CDD_TrafficRule_encode_uper;
per_type_decoder_f srem_ETSI_ITS_CDD_TrafficRule_decode_aper;
per_type_encoder_f srem_ETSI_ITS_CDD_TrafficRule_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ETSI_ITS_CDD_TrafficRule_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
