/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_RequestorPositionVector_H_
#define	_srem_ts_RequestorPositionVector_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ts_Position3D.h"
#include "etsi_its_srem_ts_coding/srem_ts_Angle.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_ts_TransmissionAndSpeed;

/* srem_ts_RequestorPositionVector */
typedef struct srem_ts_RequestorPositionVector {
	srem_ts_Position3D_t	 position;
	srem_ts_Angle_t	*heading;	/* OPTIONAL */
	struct srem_ts_TransmissionAndSpeed	*speed;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_RequestorPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_RequestorPositionVector;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ts_RequestorPositionVector_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ts_RequestorPositionVector_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ts_TransmissionAndSpeed.h"

#endif	/* _srem_ts_RequestorPositionVector_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
