/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_TimeChangeDetails_H_
#define	_srem_ts_TimeChangeDetails_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_ts_TimeMark.h"
#include "etsi_its_srem_ts_coding/srem_ts_TimeIntervalConfidence.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_ts_TimeChangeDetails */
typedef struct srem_ts_TimeChangeDetails {
	srem_ts_TimeMark_t	*startTime;	/* OPTIONAL */
	srem_ts_TimeMark_t	 minEndTime;
	srem_ts_TimeMark_t	*maxEndTime;	/* OPTIONAL */
	srem_ts_TimeMark_t	*likelyTime;	/* OPTIONAL */
	srem_ts_TimeIntervalConfidence_t	*confidence;	/* OPTIONAL */
	srem_ts_TimeMark_t	*nextTime;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ts_TimeChangeDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_TimeChangeDetails;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_ts_TimeChangeDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_ts_TimeChangeDetails_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_TimeChangeDetails_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
