/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ParkingSpaceDetailed_H_
#define	_srem_ParkingSpaceDetailed_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_Identifier2B.h"
#include "etsi_its_srem_ts_coding/srem_ParkingSpaceStatus.h"
#include "etsi_its_srem_ts_coding/srem_ParkingAreaArrangementType.h"
#include "etsi_its_srem_ts_coding/srem_ParkingOccupancyInfo.h"
#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/constr_SEQUENCE_OF.h>
#include "etsi_its_srem_ts_coding/srem_ParkingReservationType.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct srem_DeltaReferencePosition;
struct srem_DeltaPositions;
struct srem_Wgs84Angle;

/* srem_ParkingSpaceDetailed */
typedef struct srem_ParkingSpaceDetailed {
	srem_Identifier2B_t	 id;
	struct srem_DeltaReferencePosition	*location;	/* OPTIONAL */
	srem_ParkingSpaceStatus_t	 status;
	srem_ParkingAreaArrangementType_t	*arrangementType;	/* OPTIONAL */
	struct srem_DeltaPositions	*boundary;	/* OPTIONAL */
	struct srem_Wgs84Angle	*orientation;	/* OPTIONAL */
	srem_ParkingOccupancyInfo_t	 occupancyRule;
	srem_Identifier2B_t	*chargingStationId;	/* OPTIONAL */
	srem_Identifier2B_t	*accessViaLane;	/* OPTIONAL */
	struct srem_ParkingSpaceDetailed__accessViaParkingSpaces {
		A_SEQUENCE_OF(srem_Identifier2B_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *accessViaParkingSpaces;
	struct srem_ParkingSpaceDetailed__reservationType {
		A_SEQUENCE_OF(srem_ParkingReservationType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reservationType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_ParkingSpaceDetailed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ParkingSpaceDetailed;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_srem_ts_coding/srem_ETSI-ITS-CDD_DeltaReferencePosition.h"
#include "etsi_its_srem_ts_coding/srem_DeltaPositions.h"
#include "etsi_its_srem_ts_coding/srem_Wgs84Angle.h"

#endif	/* _srem_ParkingSpaceDetailed_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
