/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_CartesianPosition3d_H_
#define	_srem_CartesianPosition3d_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_srem_ts_coding/srem_CartesianCoordinate.h"
#include <etsi_its_srem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* srem_CartesianPosition3d */
typedef struct srem_CartesianPosition3d {
	srem_CartesianCoordinate_t	 xCoordinate;
	srem_CartesianCoordinate_t	 yCoordinate;
	srem_CartesianCoordinate_t	*zCoordinate;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} srem_CartesianPosition3d_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_CartesianPosition3d;
extern asn_SEQUENCE_specifics_t asn_SPC_srem_CartesianPosition3d_specs_1;
extern asn_TYPE_member_t asn_MBR_srem_CartesianPosition3d_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _srem_CartesianPosition3d_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
