/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=srem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_H_
#define	_srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_H_


#include <etsi_its_srem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_srem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode {
	srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_unavailable	= 0,
	srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_wildAnimals	= 1,
	srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_herdOfAnimals	= 2,
	srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_smallAnimals	= 3,
	srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_largeAnimals	= 4
} e_srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode;

/* srem_ts_HazardousLocation-AnimalOnTheRoadSubCauseCode */
typedef long	 srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode;
asn_struct_free_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_free;
asn_struct_print_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_print;
asn_constr_check_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_constraint;
jer_type_encoder_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_encode_jer;
per_type_decoder_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_decode_uper;
per_type_encoder_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_encode_uper;
per_type_decoder_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_decode_aper;
per_type_encoder_f srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _srem_ts_HazardousLocation_AnimalOnTheRoadSubCauseCode_H_ */
#include <etsi_its_srem_ts_coding/asn_internal.h>
