/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/SSEM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  -o \
  etsi_its_conversion/etsi_its_ssem_ts_conversion/include/etsi_its_ssem_ts_conversion \
  -t \
  ssem_ts
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
SignalStatusMessage ::= SEQUENCE {
  timeStamp       MinuteOfTheYear  OPTIONAL,
  second          DSecond,
  sequenceNumber  MsgCount         OPTIONAL,            
  status          SignalStatusList,
  regional        SEQUENCE (SIZE(1..4)) OF 
                  RegionalExtension {{Reg-SignalStatusMessage}} OPTIONAL,
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_ssem_ts_coding/ssem_ts_SignalStatusMessage.h>
#include <etsi_its_ssem_ts_conversion/convertDSecond.h>
#include <etsi_its_ssem_ts_conversion/convertMinuteOfTheYear.h>
#include <etsi_its_ssem_ts_conversion/convertMsgCount.h>
#include <etsi_its_ssem_ts_conversion/convertSignalStatusList.h>
#include <etsi_its_ssem_ts_msgs/msg/signal_status_message.hpp>
namespace ssem_ts_msgs = etsi_its_ssem_ts_msgs::msg;


namespace etsi_its_ssem_ts_conversion {

void toRos_SignalStatusMessage(const ssem_ts_SignalStatusMessage_t& in, ssem_ts_msgs::SignalStatusMessage& out) {
  if (in.timeStamp) {
    toRos_MinuteOfTheYear(*in.timeStamp, out.time_stamp);
    out.time_stamp_is_present = true;
  }
  toRos_DSecond(in.second, out.second);
  if (in.sequenceNumber) {
    toRos_MsgCount(*in.sequenceNumber, out.sequence_number);
    out.sequence_number_is_present = true;
  }
  toRos_SignalStatusList(in.status, out.status);
}

void toStruct_SignalStatusMessage(const ssem_ts_msgs::SignalStatusMessage& in, ssem_ts_SignalStatusMessage_t& out) {
  memset(&out, 0, sizeof(ssem_ts_SignalStatusMessage_t));
  if (in.time_stamp_is_present) {
    out.timeStamp = (ssem_ts_MinuteOfTheYear_t*) calloc(1, sizeof(ssem_ts_MinuteOfTheYear_t));
    toStruct_MinuteOfTheYear(in.time_stamp, *out.timeStamp);
  }
  toStruct_DSecond(in.second, out.second);
  if (in.sequence_number_is_present) {
    out.sequenceNumber = (ssem_ts_MsgCount_t*) calloc(1, sizeof(ssem_ts_MsgCount_t));
    toStruct_MsgCount(in.sequence_number, *out.sequenceNumber);
  }
  toStruct_SignalStatusList(in.status, out.status);
}

}
