/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/SSEM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/reference/ISO-TS-19091-addgrp-C-2018.asn \
  -o \
  ./etsi_its_conversion/etsi_its_ssem_ts_conversion/include/etsi_its_ssem_ts_conversion/ \
  -t \
  ssem
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
*
* Signal status extended Message
* 
* This DF includes DEs for the SSEM: protocolVersion, the SSEM message type identifier `messageID` and
* the station identifier `stationID` of the originating ITS-S and the signal status data from ETSI-ITS-DSRC.
*
* @field header: The DE `protocolVersion` is used to select the appropriate protocol decoder at the receiving ITS-S. 
*                It shall be set to 2.
*                The DE `messageID` shall be ssem(10).
* @field ssm:    contains the Signal status data as defined in ETSI-ITS-DSRC.
* 
* @category: Basic Information
* @revision: V1.3.1
*
SSEM ::= SEQUENCE {
    header  ItsPduHeader,
    ssm     SignalStatusMessage
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_ssem_coding/ssem_SSEM.h>
#include <etsi_its_ssem_conversion/convertItsPduHeader.h>
#include <etsi_its_ssem_conversion/convertSignalStatusMessage.h>
#include <etsi_its_ssem_msgs/msg/ssem.hpp>
namespace ssem_msgs = etsi_its_ssem_msgs::msg;


namespace etsi_its_ssem_conversion {

void toRos_SSEM(const ssem_SSEM_t& in, ssem_msgs::SSEM& out) {
  toRos_ItsPduHeader(in.header, out.header);
  toRos_SignalStatusMessage(in.ssm, out.ssm);
}

void toStruct_SSEM(const ssem_msgs::SSEM& in, ssem_SSEM_t& out) {
  memset(&out, 0, sizeof(ssem_SSEM_t));
  toStruct_ItsPduHeader(in.header, out.header);
  toStruct_SignalStatusMessage(in.ssm, out.ssm);
}

}
