/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SpeedValue_H_
#define	_ssem_SpeedValue_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_SpeedValue {
	ssem_SpeedValue_standstill	= 0,
	ssem_SpeedValue_oneCentimeterPerSec	= 1,
	ssem_SpeedValue_unavailable	= 16383
} e_ssem_SpeedValue;

/* ssem_SpeedValue */
typedef long	 ssem_SpeedValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_SpeedValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_SpeedValue;
asn_struct_free_f ssem_SpeedValue_free;
asn_struct_print_f ssem_SpeedValue_print;
asn_constr_check_f ssem_SpeedValue_constraint;
jer_type_encoder_f ssem_SpeedValue_encode_jer;
per_type_decoder_f ssem_SpeedValue_decode_uper;
per_type_encoder_f ssem_SpeedValue_encode_uper;
per_type_decoder_f ssem_SpeedValue_decode_aper;
per_type_encoder_f ssem_SpeedValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_SpeedValue_H_ */
#include <msg/asn_internal.h>
