/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_LongitudinalAccelerationValue_H_
#define	_ssem_LongitudinalAccelerationValue_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_LongitudinalAccelerationValue {
	ssem_LongitudinalAccelerationValue_pointOneMeterPerSecSquaredForward	= 1,
	ssem_LongitudinalAccelerationValue_pointOneMeterPerSecSquaredBackward	= -1,
	ssem_LongitudinalAccelerationValue_unavailable	= 161
} e_ssem_LongitudinalAccelerationValue;

/* ssem_LongitudinalAccelerationValue */
typedef long	 ssem_LongitudinalAccelerationValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_LongitudinalAccelerationValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_LongitudinalAccelerationValue;
asn_struct_free_f ssem_LongitudinalAccelerationValue_free;
asn_struct_print_f ssem_LongitudinalAccelerationValue_print;
asn_constr_check_f ssem_LongitudinalAccelerationValue_constraint;
jer_type_encoder_f ssem_LongitudinalAccelerationValue_encode_jer;
per_type_decoder_f ssem_LongitudinalAccelerationValue_decode_uper;
per_type_encoder_f ssem_LongitudinalAccelerationValue_encode_uper;
per_type_decoder_f ssem_LongitudinalAccelerationValue_decode_aper;
per_type_encoder_f ssem_LongitudinalAccelerationValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_LongitudinalAccelerationValue_H_ */
#include <msg/asn_internal.h>
