/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_RestrictionUserType_H_
#define	_ssem_RestrictionUserType_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_RestrictionAppliesTo.h"
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>
#include <msg/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_RestrictionUserType_PR {
	ssem_RestrictionUserType_PR_NOTHING,	/* No components present */
	ssem_RestrictionUserType_PR_basicType,
	ssem_RestrictionUserType_PR_regional
	/* Extensions may appear below */
	
} ssem_RestrictionUserType_PR;

/* Forward declarations */
struct ssem_Reg_RestrictionUserType;

/* ssem_RestrictionUserType */
typedef struct ssem_RestrictionUserType {
	ssem_RestrictionUserType_PR present;
	union ssem_RestrictionUserType_u {
		ssem_RestrictionAppliesTo_t	 basicType;
		struct ssem_RestrictionUserType__regional {
			A_SEQUENCE_OF(struct ssem_Reg_RestrictionUserType) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} regional;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_RestrictionUserType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_RestrictionUserType;
extern asn_CHOICE_specifics_t asn_SPC_ssem_RestrictionUserType_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_RestrictionUserType_1[2];
extern asn_per_constraints_t asn_PER_type_ssem_RestrictionUserType_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_RegionalExtension.h"

#endif	/* _ssem_RestrictionUserType_H_ */
#include <msg/asn_internal.h>
