/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SemiMajorAxisOrientation_H_
#define	_ssem_SemiMajorAxisOrientation_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_SemiMajorAxisOrientation */
typedef long	 ssem_SemiMajorAxisOrientation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_SemiMajorAxisOrientation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_SemiMajorAxisOrientation;
asn_struct_free_f ssem_SemiMajorAxisOrientation_free;
asn_struct_print_f ssem_SemiMajorAxisOrientation_print;
asn_constr_check_f ssem_SemiMajorAxisOrientation_constraint;
jer_type_encoder_f ssem_SemiMajorAxisOrientation_encode_jer;
per_type_decoder_f ssem_SemiMajorAxisOrientation_decode_uper;
per_type_encoder_f ssem_SemiMajorAxisOrientation_encode_uper;
per_type_decoder_f ssem_SemiMajorAxisOrientation_decode_aper;
per_type_encoder_f ssem_SemiMajorAxisOrientation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_SemiMajorAxisOrientation_H_ */
#include <msg/asn_internal.h>
