/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_CenDsrcTollingZone_H_
#define	_ssem_CenDsrcTollingZone_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_Latitude.h"
#include "msg/ssem_Longitude.h"
#include "msg/ssem_CenDsrcTollingZoneID.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_CenDsrcTollingZone */
typedef struct ssem_CenDsrcTollingZone {
	ssem_Latitude_t	 protectedZoneLatitude;
	ssem_Longitude_t	 protectedZoneLongitude;
	ssem_CenDsrcTollingZoneID_t	*cenDsrcTollingZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_CenDsrcTollingZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_CenDsrcTollingZone;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_CenDsrcTollingZone_H_ */
#include <msg/asn_internal.h>
