/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ProtectedCommunicationZonesRSU_H_
#define	_ssem_ProtectedCommunicationZonesRSU_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_ProtectedCommunicationZone;

/* ssem_ProtectedCommunicationZonesRSU */
typedef struct ssem_ProtectedCommunicationZonesRSU {
	A_SEQUENCE_OF(struct ssem_ProtectedCommunicationZone) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ProtectedCommunicationZonesRSU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ProtectedCommunicationZonesRSU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_ProtectedCommunicationZone.h"

#endif	/* _ssem_ProtectedCommunicationZonesRSU_H_ */
#include <msg/asn_internal.h>
