/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ThrottleConfidence_H_
#define	_ssem_ThrottleConfidence_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ThrottleConfidence {
	ssem_ThrottleConfidence_unavailable	= 0,
	ssem_ThrottleConfidence_prec10percent	= 1,
	ssem_ThrottleConfidence_prec1percent	= 2,
	ssem_ThrottleConfidence_prec0_5percent	= 3
} e_ssem_ThrottleConfidence;

/* ssem_ThrottleConfidence */
typedef long	 ssem_ThrottleConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ThrottleConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ThrottleConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_ThrottleConfidence_specs_1;
asn_struct_free_f ssem_ThrottleConfidence_free;
asn_struct_print_f ssem_ThrottleConfidence_print;
asn_constr_check_f ssem_ThrottleConfidence_constraint;
jer_type_encoder_f ssem_ThrottleConfidence_encode_jer;
per_type_decoder_f ssem_ThrottleConfidence_decode_uper;
per_type_encoder_f ssem_ThrottleConfidence_encode_uper;
per_type_decoder_f ssem_ThrottleConfidence_decode_aper;
per_type_encoder_f ssem_ThrottleConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ThrottleConfidence_H_ */
#include <msg/asn_internal.h>
