/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SignalHeadLocation_H_
#define	_ssem_SignalHeadLocation_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_NodeOffsetPointXY.h"
#include "msg/ssem_DeltaAltitude.h"
#include "msg/ssem_SignalGroupID.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_SignalHeadLocation */
typedef struct ssem_SignalHeadLocation {
	ssem_NodeOffsetPointXY_t	 nodeXY;
	ssem_DeltaAltitude_t	 nodeZ;
	ssem_SignalGroupID_t	 signalGroupID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_SignalHeadLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_SignalHeadLocation;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_SignalHeadLocation_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_SignalHeadLocation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_SignalHeadLocation_H_ */
#include <msg/asn_internal.h>
