/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_GenericLane_H_
#define	_ssem_GenericLane_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_LaneID.h"
#include "msg/ssem_DescriptiveName.h"
#include "msg/ssem_ApproachID.h"
#include "msg/ssem_LaneAttributes.h"
#include "msg/ssem_AllowedManeuvers.h"
#include "msg/ssem_NodeListXY.h"
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_ConnectsToList;
struct ssem_OverlayLaneList;
struct ssem_Reg_GenericLane;

/* ssem_GenericLane */
typedef struct ssem_GenericLane {
	ssem_LaneID_t	 laneID;
	ssem_DescriptiveName_t	*name;	/* OPTIONAL */
	ssem_ApproachID_t	*ingressApproach;	/* OPTIONAL */
	ssem_ApproachID_t	*egressApproach;	/* OPTIONAL */
	ssem_LaneAttributes_t	 laneAttributes;
	ssem_AllowedManeuvers_t	*maneuvers;	/* OPTIONAL */
	ssem_NodeListXY_t	 nodeList;
	struct ssem_ConnectsToList	*connectsTo;	/* OPTIONAL */
	struct ssem_OverlayLaneList	*overlays;	/* OPTIONAL */
	struct ssem_GenericLane__regional {
		A_SEQUENCE_OF(struct ssem_Reg_GenericLane) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_GenericLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_GenericLane;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_GenericLane_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_GenericLane_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_ConnectsToList.h"
#include "msg/ssem_OverlayLaneList.h"
#include "msg/ssem_RegionalExtension.h"

#endif	/* _ssem_GenericLane_H_ */
#include <msg/asn_internal.h>
