/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PtActivation_H_
#define	_ssem_PtActivation_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_PtActivationType.h"
#include "msg/ssem_PtActivationData.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_PtActivation */
typedef struct ssem_PtActivation {
	ssem_PtActivationType_t	 ptActivationType;
	ssem_PtActivationData_t	 ptActivationData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_PtActivation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_PtActivation;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PtActivation_H_ */
#include <msg/asn_internal.h>
