/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ConnectingLane_H_
#define	_ssem_ConnectingLane_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_LaneID.h"
#include "msg/ssem_AllowedManeuvers.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_ConnectingLane */
typedef struct ssem_ConnectingLane {
	ssem_LaneID_t	 lane;
	ssem_AllowedManeuvers_t	*maneuver;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ConnectingLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ConnectingLane;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_ConnectingLane_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_ConnectingLane_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ConnectingLane_H_ */
#include <msg/asn_internal.h>
