/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_IntersectionState_addGrpC_H_
#define	_ssem_IntersectionState_addGrpC_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_PrioritizationResponseList;

/* ssem_IntersectionState-addGrpC */
typedef struct ssem_IntersectionState_addGrpC {
	struct ssem_PrioritizationResponseList	*activePrioritizations;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_IntersectionState_addGrpC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_IntersectionState_addGrpC;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_IntersectionState_addGrpC_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_IntersectionState_addGrpC_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_PrioritizationResponseList.h"

#endif	/* _ssem_IntersectionState_addGrpC_H_ */
#include <msg/asn_internal.h>
