/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SPAT_H_
#define	_ssem_SPAT_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_MinuteOfTheYear.h"
#include "msg/ssem_DescriptiveName.h"
#include "msg/ssem_IntersectionStateList.h"
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_Reg_SPAT;

/* ssem_SPAT */
typedef struct ssem_SPAT {
	ssem_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	ssem_DescriptiveName_t	*name;	/* OPTIONAL */
	ssem_IntersectionStateList_t	 intersections;
	struct ssem_SPAT__regional {
		A_SEQUENCE_OF(struct ssem_Reg_SPAT) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_SPAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_SPAT;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_RegionalExtension.h"

#endif	/* _ssem_SPAT_H_ */
#include <msg/asn_internal.h>
