/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_Node_XY_24b_H_
#define	_ssem_Node_XY_24b_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_Offset-B12.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_Node-XY-24b */
typedef struct ssem_Node_XY_24b {
	ssem_Offset_B12_t	 x;
	ssem_Offset_B12_t	 y;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_Node_XY_24b_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_Node_XY_24b;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_Node_XY_24b_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_Node_XY_24b_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_Node_XY_24b_H_ */
#include <msg/asn_internal.h>
