/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AVIAEINumberingAndDataStructures"
 * 	found in "/input/ISO14816_AVIAEINumberingAndDataStructures.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_FreightContainerData_H_
#define	_ssem_FreightContainerData_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/BIT_STRING.h>
#include <msg/NativeInteger.h>
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_FreightContainerData */
typedef struct ssem_FreightContainerData {
	BIT_STRING_t	 ownerCode;
	long	 serialNumber;
	long	 checkDigit;
	long	 length;
	long	 height;
	long	 width;
	long	 containerTypeCode;
	long	 maximumGrossMass;
	long	 tareMass;
	BIT_STRING_t	 fill;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_FreightContainerData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_FreightContainerData;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_FreightContainerData_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_FreightContainerData_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_FreightContainerData_H_ */
#include <msg/asn_internal.h>
