/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DangerousEndOfQueueSubCauseCode_H_
#define	_ssem_DangerousEndOfQueueSubCauseCode_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_DangerousEndOfQueueSubCauseCode {
	ssem_DangerousEndOfQueueSubCauseCode_unavailable	= 0,
	ssem_DangerousEndOfQueueSubCauseCode_suddenEndOfQueue	= 1,
	ssem_DangerousEndOfQueueSubCauseCode_queueOverHill	= 2,
	ssem_DangerousEndOfQueueSubCauseCode_queueAroundBend	= 3,
	ssem_DangerousEndOfQueueSubCauseCode_queueInTunnel	= 4
} e_ssem_DangerousEndOfQueueSubCauseCode;

/* ssem_DangerousEndOfQueueSubCauseCode */
typedef long	 ssem_DangerousEndOfQueueSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_DangerousEndOfQueueSubCauseCode;
asn_struct_free_f ssem_DangerousEndOfQueueSubCauseCode_free;
asn_struct_print_f ssem_DangerousEndOfQueueSubCauseCode_print;
asn_constr_check_f ssem_DangerousEndOfQueueSubCauseCode_constraint;
jer_type_encoder_f ssem_DangerousEndOfQueueSubCauseCode_encode_jer;
per_type_decoder_f ssem_DangerousEndOfQueueSubCauseCode_decode_uper;
per_type_encoder_f ssem_DangerousEndOfQueueSubCauseCode_encode_uper;
per_type_decoder_f ssem_DangerousEndOfQueueSubCauseCode_decode_aper;
per_type_encoder_f ssem_DangerousEndOfQueueSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_DangerousEndOfQueueSubCauseCode_H_ */
#include <msg/asn_internal.h>
