/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_NodeOffsetPointXY_H_
#define	_ssem_NodeOffsetPointXY_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_Node-XY-20b.h"
#include "msg/ssem_Node-XY-22b.h"
#include "msg/ssem_Node-XY-24b.h"
#include "msg/ssem_Node-XY-26b.h"
#include "msg/ssem_Node-XY-28b.h"
#include "msg/ssem_Node-XY-32b.h"
#include "msg/ssem_Node-LLmD-64b.h"
#include "msg/ssem_RegionalExtension.h"
#include <msg/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_NodeOffsetPointXY_PR {
	ssem_NodeOffsetPointXY_PR_NOTHING,	/* No components present */
	ssem_NodeOffsetPointXY_PR_node_XY1,
	ssem_NodeOffsetPointXY_PR_node_XY2,
	ssem_NodeOffsetPointXY_PR_node_XY3,
	ssem_NodeOffsetPointXY_PR_node_XY4,
	ssem_NodeOffsetPointXY_PR_node_XY5,
	ssem_NodeOffsetPointXY_PR_node_XY6,
	ssem_NodeOffsetPointXY_PR_node_LatLon,
	ssem_NodeOffsetPointXY_PR_regional
} ssem_NodeOffsetPointXY_PR;

/* ssem_NodeOffsetPointXY */
typedef struct ssem_NodeOffsetPointXY {
	ssem_NodeOffsetPointXY_PR present;
	union ssem_NodeOffsetPointXY_u {
		ssem_Node_XY_20b_t	 node_XY1;
		ssem_Node_XY_22b_t	 node_XY2;
		ssem_Node_XY_24b_t	 node_XY3;
		ssem_Node_XY_26b_t	 node_XY4;
		ssem_Node_XY_28b_t	 node_XY5;
		ssem_Node_XY_32b_t	 node_XY6;
		ssem_Node_LLmD_64b_t	 node_LatLon;
		ssem_Reg_NodeOffsetPointXY_t	 regional;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_NodeOffsetPointXY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_NodeOffsetPointXY;
extern asn_CHOICE_specifics_t asn_SPC_ssem_NodeOffsetPointXY_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_NodeOffsetPointXY_1[8];
extern asn_per_constraints_t asn_PER_type_ssem_NodeOffsetPointXY_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_NodeOffsetPointXY_H_ */
#include <msg/asn_internal.h>
