/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PrioritizationResponseStatus_H_
#define	_ssem_PrioritizationResponseStatus_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_PrioritizationResponseStatus {
	ssem_PrioritizationResponseStatus_unknown	= 0,
	ssem_PrioritizationResponseStatus_requested	= 1,
	ssem_PrioritizationResponseStatus_processing	= 2,
	ssem_PrioritizationResponseStatus_watchOtherTraffic	= 3,
	ssem_PrioritizationResponseStatus_granted	= 4,
	ssem_PrioritizationResponseStatus_rejected	= 5,
	ssem_PrioritizationResponseStatus_maxPresence	= 6,
	ssem_PrioritizationResponseStatus_reserviceLocked	= 7
	/*
	 * Enumeration is extensible
	 */
} e_ssem_PrioritizationResponseStatus;

/* ssem_PrioritizationResponseStatus */
typedef long	 ssem_PrioritizationResponseStatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_PrioritizationResponseStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_PrioritizationResponseStatus;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_PrioritizationResponseStatus_specs_1;
asn_struct_free_f ssem_PrioritizationResponseStatus_free;
asn_struct_print_f ssem_PrioritizationResponseStatus_print;
asn_constr_check_f ssem_PrioritizationResponseStatus_constraint;
jer_type_encoder_f ssem_PrioritizationResponseStatus_encode_jer;
per_type_decoder_f ssem_PrioritizationResponseStatus_decode_uper;
per_type_encoder_f ssem_PrioritizationResponseStatus_encode_uper;
per_type_decoder_f ssem_PrioritizationResponseStatus_decode_aper;
per_type_encoder_f ssem_PrioritizationResponseStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PrioritizationResponseStatus_H_ */
#include <msg/asn_internal.h>
