/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_MovementState_H_
#define	_ssem_MovementState_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_DescriptiveName.h"
#include "msg/ssem_SignalGroupID.h"
#include "msg/ssem_MovementEventList.h"
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_ManeuverAssistList;
struct ssem_Reg_MovementState;

/* ssem_MovementState */
typedef struct ssem_MovementState {
	ssem_DescriptiveName_t	*movementName;	/* OPTIONAL */
	ssem_SignalGroupID_t	 signalGroup;
	ssem_MovementEventList_t	 state_time_speed;
	struct ssem_ManeuverAssistList	*maneuverAssistList;	/* OPTIONAL */
	struct ssem_MovementState__regional {
		A_SEQUENCE_OF(struct ssem_Reg_MovementState) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_MovementState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_MovementState;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_MovementState_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_MovementState_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_ManeuverAssistList.h"
#include "msg/ssem_RegionalExtension.h"

#endif	/* _ssem_MovementState_H_ */
#include <msg/asn_internal.h>
