/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_EmissionType_H_
#define	_ssem_EmissionType_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_EmissionType {
	ssem_EmissionType_euro1	= 0,
	ssem_EmissionType_euro2	= 1,
	ssem_EmissionType_euro3	= 2,
	ssem_EmissionType_euro4	= 3,
	ssem_EmissionType_euro5	= 4,
	ssem_EmissionType_euro6	= 5
	/*
	 * Enumeration is extensible
	 */
} e_ssem_EmissionType;

/* ssem_EmissionType */
typedef long	 ssem_EmissionType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_EmissionType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_EmissionType;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_EmissionType_specs_1;
asn_struct_free_f ssem_EmissionType_free;
asn_struct_print_f ssem_EmissionType_print;
asn_constr_check_f ssem_EmissionType_constraint;
jer_type_encoder_f ssem_EmissionType_encode_jer;
per_type_decoder_f ssem_EmissionType_decode_uper;
per_type_encoder_f ssem_EmissionType_encode_uper;
per_type_decoder_f ssem_EmissionType_decode_aper;
per_type_encoder_f ssem_EmissionType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_EmissionType_H_ */
#include <msg/asn_internal.h>
