/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PosConfidenceEllipse_H_
#define	_ssem_PosConfidenceEllipse_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_SemiAxisLength.h"
#include "msg/ssem_HeadingValue.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_PosConfidenceEllipse */
typedef struct ssem_PosConfidenceEllipse {
	ssem_SemiAxisLength_t	 semiMajorConfidence;
	ssem_SemiAxisLength_t	 semiMinorConfidence;
	ssem_HeadingValue_t	 semiMajorOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_PosConfidenceEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_PosConfidenceEllipse;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_PosConfidenceEllipse_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_PosConfidenceEllipse_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PosConfidenceEllipse_H_ */
#include <msg/asn_internal.h>
