/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_MovementEvent_H_
#define	_ssem_MovementEvent_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_MovementPhaseState.h"
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_TimeChangeDetails;
struct ssem_AdvisorySpeedList;
struct ssem_Reg_MovementEvent;

/* ssem_MovementEvent */
typedef struct ssem_MovementEvent {
	ssem_MovementPhaseState_t	 eventState;
	struct ssem_TimeChangeDetails	*timing;	/* OPTIONAL */
	struct ssem_AdvisorySpeedList	*speeds;	/* OPTIONAL */
	struct ssem_MovementEvent__regional {
		A_SEQUENCE_OF(struct ssem_Reg_MovementEvent) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_MovementEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_MovementEvent;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_MovementEvent_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_MovementEvent_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_TimeChangeDetails.h"
#include "msg/ssem_AdvisorySpeedList.h"
#include "msg/ssem_RegionalExtension.h"

#endif	/* _ssem_MovementEvent_H_ */
#include <msg/asn_internal.h>
