/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PosLonCarr_H_
#define	_ssem_PosLonCarr_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_PosLonCarr {
	ssem_PosLonCarr_oneCentimeter	= 1,
	ssem_PosLonCarr_unavailable	= 127
} e_ssem_PosLonCarr;

/* ssem_PosLonCarr */
typedef long	 ssem_PosLonCarr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_PosLonCarr;
asn_struct_free_f ssem_PosLonCarr_free;
asn_struct_print_f ssem_PosLonCarr_print;
asn_constr_check_f ssem_PosLonCarr_constraint;
jer_type_encoder_f ssem_PosLonCarr_encode_jer;
per_type_decoder_f ssem_PosLonCarr_decode_uper;
per_type_encoder_f ssem_PosLonCarr_encode_uper;
per_type_decoder_f ssem_PosLonCarr_decode_aper;
per_type_encoder_f ssem_PosLonCarr_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PosLonCarr_H_ */
#include <msg/asn_internal.h>
