/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_LaneDataAttributeList_H_
#define	_ssem_LaneDataAttributeList_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_LaneDataAttribute;

/* ssem_LaneDataAttributeList */
typedef struct ssem_LaneDataAttributeList {
	A_SEQUENCE_OF(struct ssem_LaneDataAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_LaneDataAttributeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_LaneDataAttributeList;
extern asn_SET_OF_specifics_t asn_SPC_ssem_LaneDataAttributeList_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_LaneDataAttributeList_1[1];
extern asn_per_constraints_t asn_PER_type_ssem_LaneDataAttributeList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_LaneDataAttribute.h"

#endif	/* _ssem_LaneDataAttributeList_H_ */
#include <msg/asn_internal.h>
