/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_RoadSegmentList_H_
#define	_ssem_RoadSegmentList_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_RoadSegment;

/* ssem_RoadSegmentList */
typedef struct ssem_RoadSegmentList {
	A_SEQUENCE_OF(struct ssem_RoadSegment) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_RoadSegmentList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_RoadSegmentList;
extern asn_SET_OF_specifics_t asn_SPC_ssem_RoadSegmentList_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_RoadSegmentList_1[1];
extern asn_per_constraints_t asn_PER_type_ssem_RoadSegmentList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_RoadSegment.h"

#endif	/* _ssem_RoadSegmentList_H_ */
#include <msg/asn_internal.h>
