/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_RequestorPositionVector_H_
#define	_ssem_RequestorPositionVector_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_Position3D.h"
#include "msg/ssem_Angle.h"
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_TransmissionAndSpeed;

/* ssem_RequestorPositionVector */
typedef struct ssem_RequestorPositionVector {
	ssem_Position3D_t	 position;
	ssem_Angle_t	*heading;	/* OPTIONAL */
	struct ssem_TransmissionAndSpeed	*speed;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_RequestorPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_RequestorPositionVector;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_RequestorPositionVector_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_RequestorPositionVector_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_TransmissionAndSpeed.h"

#endif	/* _ssem_RequestorPositionVector_H_ */
#include <msg/asn_internal.h>
