/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SpecialTransportType_H_
#define	_ssem_SpecialTransportType_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_SpecialTransportType {
	ssem_SpecialTransportType_heavyLoad	= 0,
	ssem_SpecialTransportType_excessWidth	= 1,
	ssem_SpecialTransportType_excessLength	= 2,
	ssem_SpecialTransportType_excessHeight	= 3
} e_ssem_SpecialTransportType;

/* ssem_SpecialTransportType */
typedef BIT_STRING_t	 ssem_SpecialTransportType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_SpecialTransportType;
asn_struct_free_f ssem_SpecialTransportType_free;
asn_struct_print_f ssem_SpecialTransportType_print;
asn_constr_check_f ssem_SpecialTransportType_constraint;
jer_type_encoder_f ssem_SpecialTransportType_encode_jer;
per_type_decoder_f ssem_SpecialTransportType_decode_uper;
per_type_encoder_f ssem_SpecialTransportType_encode_uper;
per_type_decoder_f ssem_SpecialTransportType_decode_aper;
per_type_encoder_f ssem_SpecialTransportType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_SpecialTransportType_H_ */
#include <msg/asn_internal.h>
