/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PtvRequestType_H_
#define	_ssem_PtvRequestType_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_PtvRequestType {
	ssem_PtvRequestType_preRequest	= 0,
	ssem_PtvRequestType_mainRequest	= 1,
	ssem_PtvRequestType_doorCloseRequest	= 2,
	ssem_PtvRequestType_cancelRequest	= 3,
	ssem_PtvRequestType_emergencyRequest	= 4
	/*
	 * Enumeration is extensible
	 */
} e_ssem_PtvRequestType;

/* ssem_PtvRequestType */
typedef long	 ssem_PtvRequestType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_PtvRequestType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_PtvRequestType;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_PtvRequestType_specs_1;
asn_struct_free_f ssem_PtvRequestType_free;
asn_struct_print_f ssem_PtvRequestType_print;
asn_constr_check_f ssem_PtvRequestType_constraint;
jer_type_encoder_f ssem_PtvRequestType_encode_jer;
per_type_decoder_f ssem_PtvRequestType_decode_uper;
per_type_encoder_f ssem_PtvRequestType_encode_uper;
per_type_decoder_f ssem_PtvRequestType_decode_aper;
per_type_encoder_f ssem_PtvRequestType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PtvRequestType_H_ */
#include <msg/asn_internal.h>
