/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_LayerType_H_
#define	_ssem_LayerType_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_LayerType {
	ssem_LayerType_none	= 0,
	ssem_LayerType_mixedContent	= 1,
	ssem_LayerType_generalMapData	= 2,
	ssem_LayerType_intersectionData	= 3,
	ssem_LayerType_curveData	= 4,
	ssem_LayerType_roadwaySectionData	= 5,
	ssem_LayerType_parkingAreaData	= 6,
	ssem_LayerType_sharedLaneData	= 7
	/*
	 * Enumeration is extensible
	 */
} e_ssem_LayerType;

/* ssem_LayerType */
typedef long	 ssem_LayerType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_LayerType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_LayerType;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_LayerType_specs_1;
asn_struct_free_f ssem_LayerType_free;
asn_struct_print_f ssem_LayerType_print;
asn_constr_check_f ssem_LayerType_constraint;
jer_type_encoder_f ssem_LayerType_encode_jer;
per_type_decoder_f ssem_LayerType_decode_uper;
per_type_encoder_f ssem_LayerType_encode_uper;
per_type_decoder_f ssem_LayerType_decode_aper;
per_type_encoder_f ssem_LayerType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_LayerType_H_ */
#include <msg/asn_internal.h>
