/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SignalStatusMessage_H_
#define	_ssem_SignalStatusMessage_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include "msg/ssem_MinuteOfTheYear.h"
#include "msg/ssem_DSecond.h"
#include "msg/ssem_MsgCount.h"
#include "msg/ssem_SignalStatusList.h"
#include <msg/asn_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE_OF.h>
#include <msg/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_Reg_SignalStatusMessage;

/* ssem_SignalStatusMessage */
typedef struct ssem_SignalStatusMessage {
	ssem_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	ssem_DSecond_t	 second;
	ssem_MsgCount_t	*sequenceNumber;	/* OPTIONAL */
	ssem_SignalStatusList_t	 status;
	struct ssem_SignalStatusMessage__regional {
		A_SEQUENCE_OF(struct ssem_Reg_SignalStatusMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_SignalStatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_SignalStatusMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_SignalStatusMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_SignalStatusMessage_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "msg/ssem_RegionalExtension.h"

#endif	/* _ssem_SignalStatusMessage_H_ */
#include <msg/asn_internal.h>
