/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_VehicleBreakdownSubCauseCode_H_
#define	_ssem_VehicleBreakdownSubCauseCode_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_VehicleBreakdownSubCauseCode {
	ssem_VehicleBreakdownSubCauseCode_unavailable	= 0,
	ssem_VehicleBreakdownSubCauseCode_lackOfFuel	= 1,
	ssem_VehicleBreakdownSubCauseCode_lackOfBatteryPower	= 2,
	ssem_VehicleBreakdownSubCauseCode_engineProblem	= 3,
	ssem_VehicleBreakdownSubCauseCode_transmissionProblem	= 4,
	ssem_VehicleBreakdownSubCauseCode_engineCoolingProblem	= 5,
	ssem_VehicleBreakdownSubCauseCode_brakingSystemProblem	= 6,
	ssem_VehicleBreakdownSubCauseCode_steeringProblem	= 7,
	ssem_VehicleBreakdownSubCauseCode_tyrePuncture	= 8,
	ssem_VehicleBreakdownSubCauseCode_tyrePressureProblem	= 9
} e_ssem_VehicleBreakdownSubCauseCode;

/* ssem_VehicleBreakdownSubCauseCode */
typedef long	 ssem_VehicleBreakdownSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_VehicleBreakdownSubCauseCode;
asn_struct_free_f ssem_VehicleBreakdownSubCauseCode_free;
asn_struct_print_f ssem_VehicleBreakdownSubCauseCode_print;
asn_constr_check_f ssem_VehicleBreakdownSubCauseCode_constraint;
jer_type_encoder_f ssem_VehicleBreakdownSubCauseCode_encode_jer;
per_type_decoder_f ssem_VehicleBreakdownSubCauseCode_decode_uper;
per_type_encoder_f ssem_VehicleBreakdownSubCauseCode_encode_uper;
per_type_decoder_f ssem_VehicleBreakdownSubCauseCode_decode_aper;
per_type_encoder_f ssem_VehicleBreakdownSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_VehicleBreakdownSubCauseCode_H_ */
#include <msg/asn_internal.h>
