/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PositionOfOccupants_H_
#define	_ssem_PositionOfOccupants_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_PositionOfOccupants {
	ssem_PositionOfOccupants_row1LeftOccupied	= 0,
	ssem_PositionOfOccupants_row1RightOccupied	= 1,
	ssem_PositionOfOccupants_row1MidOccupied	= 2,
	ssem_PositionOfOccupants_row1NotDetectable	= 3,
	ssem_PositionOfOccupants_row1NotPresent	= 4,
	ssem_PositionOfOccupants_row2LeftOccupied	= 5,
	ssem_PositionOfOccupants_row2RightOccupied	= 6,
	ssem_PositionOfOccupants_row2MidOccupied	= 7,
	ssem_PositionOfOccupants_row2NotDetectable	= 8,
	ssem_PositionOfOccupants_row2NotPresent	= 9,
	ssem_PositionOfOccupants_row3LeftOccupied	= 10,
	ssem_PositionOfOccupants_row3RightOccupied	= 11,
	ssem_PositionOfOccupants_row3MidOccupied	= 12,
	ssem_PositionOfOccupants_row3NotDetectable	= 13,
	ssem_PositionOfOccupants_row3NotPresent	= 14,
	ssem_PositionOfOccupants_row4LeftOccupied	= 15,
	ssem_PositionOfOccupants_row4RightOccupied	= 16,
	ssem_PositionOfOccupants_row4MidOccupied	= 17,
	ssem_PositionOfOccupants_row4NotDetectable	= 18,
	ssem_PositionOfOccupants_row4NotPresent	= 19
} e_ssem_PositionOfOccupants;

/* ssem_PositionOfOccupants */
typedef BIT_STRING_t	 ssem_PositionOfOccupants_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_PositionOfOccupants;
asn_struct_free_f ssem_PositionOfOccupants_free;
asn_struct_print_f ssem_PositionOfOccupants_print;
asn_constr_check_f ssem_PositionOfOccupants_constraint;
jer_type_encoder_f ssem_PositionOfOccupants_encode_jer;
per_type_decoder_f ssem_PositionOfOccupants_decode_uper;
per_type_encoder_f ssem_PositionOfOccupants_encode_uper;
per_type_decoder_f ssem_PositionOfOccupants_decode_aper;
per_type_encoder_f ssem_PositionOfOccupants_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PositionOfOccupants_H_ */
#include <msg/asn_internal.h>
