/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_LateralAccelerationValue_H_
#define	_ssem_LateralAccelerationValue_H_


#include <msg/asn_application.h>

/* Including external dependencies */
#include <msg/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_LateralAccelerationValue {
	ssem_LateralAccelerationValue_pointOneMeterPerSecSquaredToRight	= -1,
	ssem_LateralAccelerationValue_pointOneMeterPerSecSquaredToLeft	= 1,
	ssem_LateralAccelerationValue_unavailable	= 161
} e_ssem_LateralAccelerationValue;

/* ssem_LateralAccelerationValue */
typedef long	 ssem_LateralAccelerationValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_LateralAccelerationValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_LateralAccelerationValue;
asn_struct_free_f ssem_LateralAccelerationValue_free;
asn_struct_print_f ssem_LateralAccelerationValue_print;
asn_constr_check_f ssem_LateralAccelerationValue_constraint;
jer_type_encoder_f ssem_LateralAccelerationValue_encode_jer;
per_type_decoder_f ssem_LateralAccelerationValue_decode_uper;
per_type_encoder_f ssem_LateralAccelerationValue_encode_uper;
per_type_decoder_f ssem_LateralAccelerationValue_decode_aper;
per_type_encoder_f ssem_LateralAccelerationValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_LateralAccelerationValue_H_ */
#include <msg/asn_internal.h>
