/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_NodeAttributeSetXY_H_
#define	_ssem_ETSI_ITS_DSRC_NodeAttributeSetXY_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-DSRC_Offset-B10.h"
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_NodeAttributeXYList;
struct ssem_SegmentAttributeXYList;
struct ssem_LaneDataAttributeList;
struct ssem_Reg_NodeAttributeSetXY;

/* ssem_ETSI-ITS-DSRC_NodeAttributeSetXY */
typedef struct ssem_ETSI_ITS_DSRC_NodeAttributeSetXY {
	struct ssem_NodeAttributeXYList	*localNode;	/* OPTIONAL */
	struct ssem_SegmentAttributeXYList	*disabled;	/* OPTIONAL */
	struct ssem_SegmentAttributeXYList	*enabled;	/* OPTIONAL */
	struct ssem_LaneDataAttributeList	*data;	/* OPTIONAL */
	ssem_ETSI_ITS_DSRC_Offset_B10_t	*dWidth;	/* OPTIONAL */
	ssem_ETSI_ITS_DSRC_Offset_B10_t	*dElevation;	/* OPTIONAL */
	struct ssem_ETSI_ITS_DSRC_NodeAttributeSetXY__regional {
		A_SEQUENCE_OF(struct ssem_Reg_NodeAttributeSetXY) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ETSI_ITS_DSRC_NodeAttributeSetXY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_NodeAttributeSetXY;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_ETSI_ITS_DSRC_NodeAttributeSetXY_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_ETSI_ITS_DSRC_NodeAttributeSetXY_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-DSRC_NodeAttributeXYList.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-DSRC_SegmentAttributeXYList.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-DSRC_LaneDataAttributeList.h"
#include "etsi_its_ssem_ts_coding/ssem_RegionalExtension.h"

#endif	/* _ssem_ETSI_ITS_DSRC_NodeAttributeSetXY_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
