/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_CartesianPosition3d_H_
#define	_ssem_CartesianPosition3d_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_CartesianCoordinate.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_CartesianPosition3d */
typedef struct ssem_CartesianPosition3d {
	ssem_CartesianCoordinate_t	 xCoordinate;
	ssem_CartesianCoordinate_t	 yCoordinate;
	ssem_CartesianCoordinate_t	*zCoordinate;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_CartesianPosition3d_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_CartesianPosition3d;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_CartesianPosition3d_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_CartesianPosition3d_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_CartesianPosition3d_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
