/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_CDD_DeltaReferencePosition_H_
#define	_ssem_ETSI_ITS_CDD_DeltaReferencePosition_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_DeltaLatitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_DeltaLongitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_DeltaAltitude.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_ETSI-ITS-CDD_DeltaReferencePosition */
typedef struct ssem_ETSI_ITS_CDD_DeltaReferencePosition {
	ssem_ETSI_ITS_CDD_DeltaLatitude_t	 deltaLatitude;
	ssem_ETSI_ITS_CDD_DeltaLongitude_t	 deltaLongitude;
	ssem_ETSI_ITS_CDD_DeltaAltitude_t	 deltaAltitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ETSI_ITS_CDD_DeltaReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_CDD_DeltaReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_ETSI_ITS_CDD_DeltaReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_ETSI_ITS_CDD_DeltaReferencePosition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_CDD_DeltaReferencePosition_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
