/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_AccidentSubCauseCode_H_
#define	_ssem_ts_AccidentSubCauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_AccidentSubCauseCode {
	ssem_ts_AccidentSubCauseCode_unavailable	= 0,
	ssem_ts_AccidentSubCauseCode_multiVehicleAccident	= 1,
	ssem_ts_AccidentSubCauseCode_heavyAccident	= 2,
	ssem_ts_AccidentSubCauseCode_accidentInvolvingLorry	= 3,
	ssem_ts_AccidentSubCauseCode_accidentInvolvingBus	= 4,
	ssem_ts_AccidentSubCauseCode_accidentInvolvingHazardousMaterials	= 5,
	ssem_ts_AccidentSubCauseCode_accidentOnOppositeLane	= 6,
	ssem_ts_AccidentSubCauseCode_unsecuredAccident	= 7,
	ssem_ts_AccidentSubCauseCode_assistanceRequested	= 8
} e_ssem_ts_AccidentSubCauseCode;

/* ssem_ts_AccidentSubCauseCode */
typedef long	 ssem_ts_AccidentSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_AccidentSubCauseCode;
asn_struct_free_f ssem_ts_AccidentSubCauseCode_free;
asn_struct_print_f ssem_ts_AccidentSubCauseCode_print;
asn_constr_check_f ssem_ts_AccidentSubCauseCode_constraint;
jer_type_encoder_f ssem_ts_AccidentSubCauseCode_encode_jer;
per_type_decoder_f ssem_ts_AccidentSubCauseCode_decode_uper;
per_type_encoder_f ssem_ts_AccidentSubCauseCode_encode_uper;
per_type_decoder_f ssem_ts_AccidentSubCauseCode_decode_aper;
per_type_encoder_f ssem_ts_AccidentSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ts_AccidentSubCauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
