/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_TimeConfidence_H_
#define	_ssem_ETSI_ITS_DSRC_TimeConfidence_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_DSRC_TimeConfidence {
	ssem_ETSI_ITS_DSRC_TimeConfidence_unavailable	= 0,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_100_000	= 1,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_050_000	= 2,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_020_000	= 3,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_010_000	= 4,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_002_000	= 5,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_001_000	= 6,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_500	= 7,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_200	= 8,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_100	= 9,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_050	= 10,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_020	= 11,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_010	= 12,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_005	= 13,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_002	= 14,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_001	= 15,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_5	= 16,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_2	= 17,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_1	= 18,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_05	= 19,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_02	= 20,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_01	= 21,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_005	= 22,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_002	= 23,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_001	= 24,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_5	= 25,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_2	= 26,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_1	= 27,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_05	= 28,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_02	= 29,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_01	= 30,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_005	= 31,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_002	= 32,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_001	= 33,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_000_5	= 34,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_000_2	= 35,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_000_1	= 36,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_000_05	= 37,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_000_02	= 38,
	ssem_ETSI_ITS_DSRC_TimeConfidence_time_000_000_000_000_01	= 39
} e_ssem_ETSI_ITS_DSRC_TimeConfidence;

/* ssem_ETSI-ITS-DSRC_TimeConfidence */
typedef long	 ssem_ETSI_ITS_DSRC_TimeConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_TimeConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_TimeConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_ETSI_ITS_DSRC_TimeConfidence_specs_1;
asn_struct_free_f ssem_ETSI_ITS_DSRC_TimeConfidence_free;
asn_struct_print_f ssem_ETSI_ITS_DSRC_TimeConfidence_print;
asn_constr_check_f ssem_ETSI_ITS_DSRC_TimeConfidence_constraint;
jer_type_encoder_f ssem_ETSI_ITS_DSRC_TimeConfidence_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_DSRC_TimeConfidence_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_TimeConfidence_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_DSRC_TimeConfidence_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_TimeConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_DSRC_TimeConfidence_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
