/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_IntersectionState_H_
#define	_ssem_DSRC_IntersectionState_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_DescriptiveName.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_IntersectionReferenceID.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_MsgCount.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_IntersectionStatusObject.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_MinuteOfTheYear.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_DSecond.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_MovementList.h"
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_EnabledLaneList;
struct ssem_ManeuverAssistList;
struct ssem_Reg_IntersectionState;

/* ssem_DSRC_IntersectionState */
typedef struct ssem_DSRC_IntersectionState {
	ssem_DSRC_DescriptiveName_t	*name;	/* OPTIONAL */
	ssem_DSRC_IntersectionReferenceID_t	 id;
	ssem_DSRC_MsgCount_t	 revision;
	ssem_DSRC_IntersectionStatusObject_t	 status;
	ssem_DSRC_MinuteOfTheYear_t	*moy;	/* OPTIONAL */
	ssem_DSRC_DSecond_t	*timeStamp;	/* OPTIONAL */
	struct ssem_EnabledLaneList	*enabledLanes;	/* OPTIONAL */
	ssem_DSRC_MovementList_t	 states;
	struct ssem_ManeuverAssistList	*maneuverAssistList;	/* OPTIONAL */
	struct ssem_DSRC_IntersectionState__regional {
		A_SEQUENCE_OF(struct ssem_Reg_IntersectionState) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_DSRC_IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_IntersectionState;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_DSRC_IntersectionState_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_DSRC_IntersectionState_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_EnabledLaneList.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_ManeuverAssistList.h"
#include "etsi_its_ssem_ts_coding/ssem_RegionalExtension.h"

#endif	/* _ssem_DSRC_IntersectionState_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
