/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_OtherSubClass_H_
#define	_ssem_OtherSubClass_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_OtherSubClass {
	ssem_OtherSubClass_unknown	= 0,
	ssem_OtherSubClass_singleObject	= 1,
	ssem_OtherSubClass_multipleObjects	= 2,
	ssem_OtherSubClass_bulkMaterial	= 3
} e_ssem_OtherSubClass;

/* ssem_OtherSubClass */
typedef long	 ssem_OtherSubClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_OtherSubClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_OtherSubClass;
asn_struct_free_f ssem_OtherSubClass_free;
asn_struct_print_f ssem_OtherSubClass_print;
asn_constr_check_f ssem_OtherSubClass_constraint;
jer_type_encoder_f ssem_OtherSubClass_encode_jer;
per_type_decoder_f ssem_OtherSubClass_decode_uper;
per_type_encoder_f ssem_OtherSubClass_encode_uper;
per_type_decoder_f ssem_OtherSubClass_decode_aper;
per_type_encoder_f ssem_OtherSubClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_OtherSubClass_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
