/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_AccelerationControl_H_
#define	_ssem_ts_AccelerationControl_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_AccelerationControl {
	ssem_ts_AccelerationControl_brakePedalEngaged	= 0,
	ssem_ts_AccelerationControl_gasPedalEngaged	= 1,
	ssem_ts_AccelerationControl_emergencyBrakeEngaged	= 2,
	ssem_ts_AccelerationControl_collisionWarningEngaged	= 3,
	ssem_ts_AccelerationControl_accEngaged	= 4,
	ssem_ts_AccelerationControl_cruiseControlEngaged	= 5,
	ssem_ts_AccelerationControl_speedLimiterEngaged	= 6
} e_ssem_ts_AccelerationControl;

/* ssem_ts_AccelerationControl */
typedef BIT_STRING_t	 ssem_ts_AccelerationControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_AccelerationControl;
asn_struct_free_f ssem_ts_AccelerationControl_free;
asn_struct_print_f ssem_ts_AccelerationControl_print;
asn_constr_check_f ssem_ts_AccelerationControl_constraint;
jer_type_encoder_f ssem_ts_AccelerationControl_encode_jer;
per_type_decoder_f ssem_ts_AccelerationControl_decode_uper;
per_type_encoder_f ssem_ts_AccelerationControl_encode_uper;
per_type_decoder_f ssem_ts_AccelerationControl_decode_aper;
per_type_encoder_f ssem_ts_AccelerationControl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ts_AccelerationControl_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
