/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_H_
#define	_ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_DSRC_RestrictionAppliesTo {
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_none	= 0,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_equippedTransit	= 1,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_equippedTaxis	= 2,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_equippedOther	= 3,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_emissionCompliant	= 4,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_equippedBicycle	= 5,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_weightCompliant	= 6,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_heightCompliant	= 7,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_pedestrians	= 8,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_slowMovingPersons	= 9,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_wheelchairUsers	= 10,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_visualDisabilities	= 11,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_audioDisabilities	= 12,
	ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_otherUnknownDisabilities	= 13
	/*
	 * Enumeration is extensible
	 */
} e_ssem_ETSI_ITS_DSRC_RestrictionAppliesTo;

/* ssem_ETSI-ITS-DSRC_RestrictionAppliesTo */
typedef long	 ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_RestrictionAppliesTo;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_specs_1;
asn_struct_free_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_free;
asn_struct_print_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_print;
asn_constr_check_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_constraint;
jer_type_encoder_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_DSRC_RestrictionAppliesTo_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
