/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_SignalRequestPackage_H_
#define	_ssem_DSRC_SignalRequestPackage_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_SignalRequest.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_MinuteOfTheYear.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_DSecond.h"
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_Reg_SignalRequestPackage;

/* ssem_DSRC_SignalRequestPackage */
typedef struct ssem_DSRC_SignalRequestPackage {
	ssem_DSRC_SignalRequest_t	 request;
	ssem_DSRC_MinuteOfTheYear_t	*minute;	/* OPTIONAL */
	ssem_DSRC_DSecond_t	*second;	/* OPTIONAL */
	ssem_DSRC_DSecond_t	*duration;	/* OPTIONAL */
	struct ssem_DSRC_SignalRequestPackage__regional {
		A_SEQUENCE_OF(struct ssem_Reg_SignalRequestPackage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_DSRC_SignalRequestPackage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_SignalRequestPackage;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_DSRC_SignalRequestPackage_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_DSRC_SignalRequestPackage_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_RegionalExtension.h"

#endif	/* _ssem_DSRC_SignalRequestPackage_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
