/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_EllipticalShape_H_
#define	_ssem_EllipticalShape_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_StandardLength12b.h"
#include "etsi_its_ssem_ts_coding/ssem_CartesianAngleValue.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_CartesianPosition3d;

/* ssem_EllipticalShape */
typedef struct ssem_EllipticalShape {
	struct ssem_CartesianPosition3d	*shapeReferencePoint;	/* OPTIONAL */
	ssem_StandardLength12b_t	 semiMajorAxisLength;
	ssem_StandardLength12b_t	 semiMinorAxisLength;
	ssem_CartesianAngleValue_t	*orientation;	/* OPTIONAL */
	ssem_StandardLength12b_t	*height;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_EllipticalShape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_EllipticalShape;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_EllipticalShape_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_EllipticalShape_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_CartesianPosition3d.h"

#endif	/* _ssem_EllipticalShape_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
