/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_H_
#define	_ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode {
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_unavailable	= 0,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_emergencyVehicles	= 1,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_rescueHelicopterLanding	= 2,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_policeActivityOngoing	= 3,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_medicalEmergencyOngoing	= 4,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_childAbductionInProgress_deprecated	= 5,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_prioritizedVehicle	= 6,
	ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_rescueAndRecoveryVehicle	= 7
} e_ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode;

/* ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode */
typedef long	 ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode;
asn_struct_free_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_free;
asn_struct_print_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_print;
asn_constr_check_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_constraint;
jer_type_encoder_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_encode_jer;
per_type_decoder_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_decode_uper;
per_type_encoder_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_encode_uper;
per_type_decoder_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_decode_aper;
per_type_encoder_f ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
