/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_FullPositionVector_H_
#define	_ssem_DSRC_FullPositionVector_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ITS-Container_Longitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ITS-Container_Latitude.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_Elevation.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_HeadingDSRC.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_TimeConfidence.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_DDateTime;
struct ssem_TransmissionAndSpeed;
struct ssem_PositionalAccuracy;
struct ssem_PositionConfidenceSet;
struct ssem_SpeedandHeadingandThrottleConfidence;

/* ssem_DSRC_FullPositionVector */
typedef struct ssem_DSRC_FullPositionVector {
	struct ssem_DDateTime	*utcTime;	/* OPTIONAL */
	ssem_ITS_Container_Longitude_t	 Long;
	ssem_ITS_Container_Latitude_t	 lat;
	ssem_DSRC_Elevation_t	*elevation;	/* OPTIONAL */
	ssem_DSRC_HeadingDSRC_t	*heading;	/* OPTIONAL */
	struct ssem_TransmissionAndSpeed	*speed;	/* OPTIONAL */
	struct ssem_PositionalAccuracy	*posAccuracy;	/* OPTIONAL */
	ssem_DSRC_TimeConfidence_t	*timeConfidence;	/* OPTIONAL */
	struct ssem_PositionConfidenceSet	*posConfidence;	/* OPTIONAL */
	struct ssem_SpeedandHeadingandThrottleConfidence	*speedConfidence;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_DSRC_FullPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_FullPositionVector;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_DSRC_FullPositionVector_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_DSRC_FullPositionVector_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_DDateTime.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_TransmissionAndSpeed.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_PositionalAccuracy.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_PositionConfidenceSet.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_SpeedandHeadingandThrottleConfidence.h"

#endif	/* _ssem_DSRC_FullPositionVector_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
