/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_LowerTriangularPositiveSemidefiniteMatrix_H_
#define	_ssem_LowerTriangularPositiveSemidefiniteMatrix_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_MatrixIncludedComponents.h"
#include "etsi_its_ssem_ts_coding/ssem_LowerTriangularPositiveSemidefiniteMatrixColumns.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_LowerTriangularPositiveSemidefiniteMatrix */
typedef struct ssem_LowerTriangularPositiveSemidefiniteMatrix {
	ssem_MatrixIncludedComponents_t	 componentsIncludedIntheMatrix;
	ssem_LowerTriangularPositiveSemidefiniteMatrixColumns_t	 matrix;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_LowerTriangularPositiveSemidefiniteMatrix_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_LowerTriangularPositiveSemidefiniteMatrix;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_LowerTriangularPositiveSemidefiniteMatrix_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_LowerTriangularPositiveSemidefiniteMatrix_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_LowerTriangularPositiveSemidefiniteMatrix_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
