/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SSEM-PDU-Descriptions"
 * 	found in "/input/SSEM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SSEM_H_
#define	_ssem_SSEM_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_ItsPduHeader.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-DSRC_SignalStatusMessage.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_SSEM */
typedef struct ssem_SSEM {
	ssem_ETSI_ITS_CDD_ItsPduHeader_t	 header;
	ssem_ETSI_ITS_DSRC_SignalStatusMessage_t	 ssm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_SSEM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_SSEM;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_SSEM_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
