/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_CDD_CurvatureConfidence_H_
#define	_ssem_ETSI_ITS_CDD_CurvatureConfidence_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_CDD_CurvatureConfidence {
	ssem_ETSI_ITS_CDD_CurvatureConfidence_onePerMeter_0_00002	= 0,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_onePerMeter_0_0001	= 1,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_onePerMeter_0_0005	= 2,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_onePerMeter_0_002	= 3,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_onePerMeter_0_01	= 4,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_onePerMeter_0_1	= 5,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_outOfRange	= 6,
	ssem_ETSI_ITS_CDD_CurvatureConfidence_unavailable	= 7
} e_ssem_ETSI_ITS_CDD_CurvatureConfidence;

/* ssem_ETSI-ITS-CDD_CurvatureConfidence */
typedef long	 ssem_ETSI_ITS_CDD_CurvatureConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_CDD_CurvatureConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_CDD_CurvatureConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_ETSI_ITS_CDD_CurvatureConfidence_specs_1;
asn_struct_free_f ssem_ETSI_ITS_CDD_CurvatureConfidence_free;
asn_struct_print_f ssem_ETSI_ITS_CDD_CurvatureConfidence_print;
asn_constr_check_f ssem_ETSI_ITS_CDD_CurvatureConfidence_constraint;
jer_type_encoder_f ssem_ETSI_ITS_CDD_CurvatureConfidence_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_CDD_CurvatureConfidence_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_CDD_CurvatureConfidence_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_CDD_CurvatureConfidence_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_CDD_CurvatureConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_CDD_CurvatureConfidence_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
