/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_AutomationControl_H_
#define	_ssem_AutomationControl_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_AutomationControl {
	ssem_AutomationControl_emergencySteeringSystemEngaged	= 0,
	ssem_AutomationControl_autonomousEmergencySteeringEngaged	= 1,
	ssem_AutomationControl_automaticLaneChangeEngaged	= 2,
	ssem_AutomationControl_laneKeepingAssistEngaged	= 3,
	ssem_AutomationControl_assistedParkingLateralEngaged	= 4,
	ssem_AutomationControl_emergencyAssistEngaged	= 5
} e_ssem_AutomationControl;

/* ssem_AutomationControl */
typedef BIT_STRING_t	 ssem_AutomationControl_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_AutomationControl_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_AutomationControl;
asn_struct_free_f ssem_AutomationControl_free;
asn_struct_print_f ssem_AutomationControl_print;
asn_constr_check_f ssem_AutomationControl_constraint;
jer_type_encoder_f ssem_AutomationControl_encode_jer;
per_type_decoder_f ssem_AutomationControl_decode_uper;
per_type_encoder_f ssem_AutomationControl_encode_uper;
per_type_decoder_f ssem_AutomationControl_decode_aper;
per_type_encoder_f ssem_AutomationControl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_AutomationControl_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
