/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_SpeedLimitType_H_
#define	_ssem_ETSI_ITS_DSRC_SpeedLimitType_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_DSRC_SpeedLimitType {
	ssem_ETSI_ITS_DSRC_SpeedLimitType_unknown	= 0,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_maxSpeedInSchoolZone	= 1,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_maxSpeedInSchoolZoneWhenChildrenArePresent	= 2,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_maxSpeedInConstructionZone	= 3,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_vehicleMinSpeed	= 4,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_vehicleMaxSpeed	= 5,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_vehicleNightMaxSpeed	= 6,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_truckMinSpeed	= 7,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_truckMaxSpeed	= 8,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_truckNightMaxSpeed	= 9,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_vehiclesWithTrailersMinSpeed	= 10,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_vehiclesWithTrailersMaxSpeed	= 11,
	ssem_ETSI_ITS_DSRC_SpeedLimitType_vehiclesWithTrailersNightMaxSpeed	= 12
	/*
	 * Enumeration is extensible
	 */
} e_ssem_ETSI_ITS_DSRC_SpeedLimitType;

/* ssem_ETSI-ITS-DSRC_SpeedLimitType */
typedef long	 ssem_ETSI_ITS_DSRC_SpeedLimitType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_SpeedLimitType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_SpeedLimitType;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_ETSI_ITS_DSRC_SpeedLimitType_specs_1;
asn_struct_free_f ssem_ETSI_ITS_DSRC_SpeedLimitType_free;
asn_struct_print_f ssem_ETSI_ITS_DSRC_SpeedLimitType_print;
asn_constr_check_f ssem_ETSI_ITS_DSRC_SpeedLimitType_constraint;
jer_type_encoder_f ssem_ETSI_ITS_DSRC_SpeedLimitType_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_DSRC_SpeedLimitType_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_SpeedLimitType_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_DSRC_SpeedLimitType_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_SpeedLimitType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_DSRC_SpeedLimitType_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
