/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicRegistrationIdentificationVehicleDataModule"
 * 	found in "/input/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_Iso3833VehicleType_H_
#define	_ssem_ts_Iso3833VehicleType_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_Iso3833VehicleType {
	ssem_ts_Iso3833VehicleType_passengerCar	= 0,
	ssem_ts_Iso3833VehicleType_saloon	= 1,
	ssem_ts_Iso3833VehicleType_convertibleSaloon	= 2,
	ssem_ts_Iso3833VehicleType_pullmanSaloon	= 3,
	ssem_ts_Iso3833VehicleType_stationWagon	= 4,
	ssem_ts_Iso3833VehicleType_truckStationWagon	= 5,
	ssem_ts_Iso3833VehicleType_coupe	= 6,
	ssem_ts_Iso3833VehicleType_convertible	= 7,
	ssem_ts_Iso3833VehicleType_multipurposePassengerCar	= 8,
	ssem_ts_Iso3833VehicleType_forwardControlPassengerCar	= 9,
	ssem_ts_Iso3833VehicleType_specialPassengerCar	= 10,
	ssem_ts_Iso3833VehicleType_bus	= 11,
	ssem_ts_Iso3833VehicleType_minibus	= 12,
	ssem_ts_Iso3833VehicleType_urbanBus	= 13,
	ssem_ts_Iso3833VehicleType_interurbanCoach	= 14,
	ssem_ts_Iso3833VehicleType_longDistanceCoach	= 15,
	ssem_ts_Iso3833VehicleType_articulatedBus	= 16,
	ssem_ts_Iso3833VehicleType_trolleyBus	= 17,
	ssem_ts_Iso3833VehicleType_specialBus	= 18,
	ssem_ts_Iso3833VehicleType_commercialVehicle	= 19,
	ssem_ts_Iso3833VehicleType_specialCommercialVehicle	= 20,
	ssem_ts_Iso3833VehicleType_specialVehicle	= 21,
	ssem_ts_Iso3833VehicleType_trailingTowingVehicle	= 22,
	ssem_ts_Iso3833VehicleType_semiTrailerTowingVehicle	= 23,
	ssem_ts_Iso3833VehicleType_trailer	= 24,
	ssem_ts_Iso3833VehicleType_busTrailer	= 25,
	ssem_ts_Iso3833VehicleType_generalPurposeTrailer	= 26,
	ssem_ts_Iso3833VehicleType_caravan	= 27,
	ssem_ts_Iso3833VehicleType_specialTrailer	= 28,
	ssem_ts_Iso3833VehicleType_semiTrailer	= 29,
	ssem_ts_Iso3833VehicleType_busSemiTrailer	= 30,
	ssem_ts_Iso3833VehicleType_generalPurposeSemiTrailer	= 31,
	ssem_ts_Iso3833VehicleType_specialSemiTrailer	= 32,
	ssem_ts_Iso3833VehicleType_roadTrain	= 33,
	ssem_ts_Iso3833VehicleType_passengerRoadTrain	= 34,
	ssem_ts_Iso3833VehicleType_articulatedRoadTrain	= 35,
	ssem_ts_Iso3833VehicleType_doubleRoadTrain	= 36,
	ssem_ts_Iso3833VehicleType_compositeRoadTrain	= 37,
	ssem_ts_Iso3833VehicleType_specialRoadTrain	= 38,
	ssem_ts_Iso3833VehicleType_moped	= 39,
	ssem_ts_Iso3833VehicleType_motorCycle	= 40
} e_ssem_ts_Iso3833VehicleType;

/* ssem_ts_Iso3833VehicleType */
typedef long	 ssem_ts_Iso3833VehicleType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ts_Iso3833VehicleType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_Iso3833VehicleType;
asn_struct_free_f ssem_ts_Iso3833VehicleType_free;
asn_struct_print_f ssem_ts_Iso3833VehicleType_print;
asn_constr_check_f ssem_ts_Iso3833VehicleType_constraint;
jer_type_encoder_f ssem_ts_Iso3833VehicleType_encode_jer;
per_type_decoder_f ssem_ts_Iso3833VehicleType_decode_uper;
per_type_encoder_f ssem_ts_Iso3833VehicleType_encode_uper;
per_type_decoder_f ssem_ts_Iso3833VehicleType_decode_aper;
per_type_encoder_f ssem_ts_Iso3833VehicleType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ts_Iso3833VehicleType_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
