/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_AdhesionSubCauseCode_H_
#define	_ssem_AdhesionSubCauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_AdhesionSubCauseCode {
	ssem_AdhesionSubCauseCode_unavailable	= 0,
	ssem_AdhesionSubCauseCode_heavyFrostOnRoad	= 1,
	ssem_AdhesionSubCauseCode_fuelOnRoad	= 2,
	ssem_AdhesionSubCauseCode_mudOnRoad	= 3,
	ssem_AdhesionSubCauseCode_snowOnRoad	= 4,
	ssem_AdhesionSubCauseCode_iceOnRoad	= 5,
	ssem_AdhesionSubCauseCode_blackIceOnRoad	= 6,
	ssem_AdhesionSubCauseCode_oilOnRoad	= 7,
	ssem_AdhesionSubCauseCode_looseChippings	= 8,
	ssem_AdhesionSubCauseCode_instantBlackIce	= 9,
	ssem_AdhesionSubCauseCode_roadsSalted	= 10,
	ssem_AdhesionSubCauseCode_flooding	= 11,
	ssem_AdhesionSubCauseCode_waterOnRoad	= 12
} e_ssem_AdhesionSubCauseCode;

/* ssem_AdhesionSubCauseCode */
typedef long	 ssem_AdhesionSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_AdhesionSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_AdhesionSubCauseCode;
asn_struct_free_f ssem_AdhesionSubCauseCode_free;
asn_struct_print_f ssem_AdhesionSubCauseCode_print;
asn_constr_check_f ssem_AdhesionSubCauseCode_constraint;
jer_type_encoder_f ssem_AdhesionSubCauseCode_encode_jer;
per_type_decoder_f ssem_AdhesionSubCauseCode_decode_uper;
per_type_encoder_f ssem_AdhesionSubCauseCode_encode_uper;
per_type_decoder_f ssem_AdhesionSubCauseCode_decode_aper;
per_type_encoder_f ssem_AdhesionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_AdhesionSubCauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
