/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_SignalStatusList_H_
#define	_ssem_ETSI_ITS_DSRC_SignalStatusList_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_SignalStatus;

/* ssem_ETSI-ITS-DSRC_SignalStatusList */
typedef struct ssem_ETSI_ITS_DSRC_SignalStatusList {
	A_SEQUENCE_OF(struct ssem_SignalStatus) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ETSI_ITS_DSRC_SignalStatusList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_SignalStatusList;
extern asn_SET_OF_specifics_t asn_SPC_ssem_ETSI_ITS_DSRC_SignalStatusList_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_ETSI_ITS_DSRC_SignalStatusList_1[1];
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_SignalStatusList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-DSRC_SignalStatus.h"

#endif	/* _ssem_ETSI_ITS_DSRC_SignalStatusList_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
