/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PriorityLevel_H_
#define	_ssem_PriorityLevel_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_PriorityLevel */
typedef long	 ssem_PriorityLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_PriorityLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_PriorityLevel;
asn_struct_free_f ssem_PriorityLevel_free;
asn_struct_print_f ssem_PriorityLevel_print;
asn_constr_check_f ssem_PriorityLevel_constraint;
jer_type_encoder_f ssem_PriorityLevel_encode_jer;
per_type_decoder_f ssem_PriorityLevel_decode_uper;
per_type_encoder_f ssem_PriorityLevel_encode_uper;
per_type_decoder_f ssem_PriorityLevel_decode_aper;
per_type_encoder_f ssem_PriorityLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_PriorityLevel_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
