/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_VehicleLengthValue_H_
#define	_ssem_ts_VehicleLengthValue_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_VehicleLengthValue {
	ssem_ts_VehicleLengthValue_tenCentimeters	= 1,
	ssem_ts_VehicleLengthValue_outOfRange	= 1022,
	ssem_ts_VehicleLengthValue_unavailable	= 1023
} e_ssem_ts_VehicleLengthValue;

/* ssem_ts_VehicleLengthValue */
typedef long	 ssem_ts_VehicleLengthValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ts_VehicleLengthValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_VehicleLengthValue;
asn_struct_free_f ssem_ts_VehicleLengthValue_free;
asn_struct_print_f ssem_ts_VehicleLengthValue_print;
asn_constr_check_f ssem_ts_VehicleLengthValue_constraint;
jer_type_encoder_f ssem_ts_VehicleLengthValue_encode_jer;
per_type_decoder_f ssem_ts_VehicleLengthValue_decode_uper;
per_type_encoder_f ssem_ts_VehicleLengthValue_encode_uper;
per_type_decoder_f ssem_ts_VehicleLengthValue_decode_aper;
per_type_encoder_f ssem_ts_VehicleLengthValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ts_VehicleLengthValue_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
