/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_H_
#define	_ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_CDD_RelevanceTrafficDirection {
	ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_allTrafficDirections	= 0,
	ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_upstreamTraffic	= 1,
	ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_downstreamTraffic	= 2,
	ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_oppositeTraffic	= 3
} e_ssem_ETSI_ITS_CDD_RelevanceTrafficDirection;

/* ssem_ETSI-ITS-CDD_RelevanceTrafficDirection */
typedef long	 ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_CDD_RelevanceTrafficDirection;
asn_struct_free_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_free;
asn_struct_print_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_print;
asn_constr_check_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_constraint;
jer_type_encoder_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_CDD_RelevanceTrafficDirection_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
