/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_LaneDirection_H_
#define	_ssem_DSRC_LaneDirection_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_DSRC_LaneDirection {
	ssem_DSRC_LaneDirection_ingressPath	= 0,
	ssem_DSRC_LaneDirection_egressPath	= 1
} e_ssem_DSRC_LaneDirection;

/* ssem_DSRC_LaneDirection */
typedef BIT_STRING_t	 ssem_DSRC_LaneDirection_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_DSRC_LaneDirection_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_LaneDirection;
asn_struct_free_f ssem_DSRC_LaneDirection_free;
asn_struct_print_f ssem_DSRC_LaneDirection_print;
asn_constr_check_f ssem_DSRC_LaneDirection_constraint;
jer_type_encoder_f ssem_DSRC_LaneDirection_encode_jer;
per_type_decoder_f ssem_DSRC_LaneDirection_decode_uper;
per_type_encoder_f ssem_DSRC_LaneDirection_encode_uper;
per_type_decoder_f ssem_DSRC_LaneDirection_decode_aper;
per_type_encoder_f ssem_DSRC_LaneDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_DSRC_LaneDirection_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
