/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ITS_Container_OpeningDaysHours_H_
#define	_ssem_ITS_Container_OpeningDaysHours_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_ITS-Container_OpeningDaysHours */
typedef UTF8String_t	 ssem_ITS_Container_OpeningDaysHours_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ITS_Container_OpeningDaysHours;
asn_struct_free_f ssem_ITS_Container_OpeningDaysHours_free;
asn_struct_print_f ssem_ITS_Container_OpeningDaysHours_print;
asn_constr_check_f ssem_ITS_Container_OpeningDaysHours_constraint;
jer_type_encoder_f ssem_ITS_Container_OpeningDaysHours_encode_jer;
per_type_decoder_f ssem_ITS_Container_OpeningDaysHours_decode_uper;
per_type_encoder_f ssem_ITS_Container_OpeningDaysHours_encode_uper;
per_type_decoder_f ssem_ITS_Container_OpeningDaysHours_decode_aper;
per_type_encoder_f ssem_ITS_Container_OpeningDaysHours_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ITS_Container_OpeningDaysHours_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
