/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_Shape_H_
#define	_ssem_Shape_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_RectangularShape.h"
#include "etsi_its_ssem_ts_coding/ssem_CircularShape.h"
#include "etsi_its_ssem_ts_coding/ssem_PolygonalShape.h"
#include "etsi_its_ssem_ts_coding/ssem_EllipticalShape.h"
#include "etsi_its_ssem_ts_coding/ssem_RadialShape.h"
#include "etsi_its_ssem_ts_coding/ssem_RadialShapes.h"
#include <etsi_its_ssem_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_Shape_PR {
	ssem_Shape_PR_NOTHING,	/* No components present */
	ssem_Shape_PR_rectangular,
	ssem_Shape_PR_circular,
	ssem_Shape_PR_polygonal,
	ssem_Shape_PR_elliptical,
	ssem_Shape_PR_radial,
	ssem_Shape_PR_radialShapes
	/* Extensions may appear below */
	
} ssem_Shape_PR;

/* ssem_Shape */
typedef struct ssem_Shape {
	ssem_Shape_PR present;
	union ssem_Shape_u {
		ssem_RectangularShape_t	 rectangular;
		ssem_CircularShape_t	 circular;
		ssem_PolygonalShape_t	 polygonal;
		ssem_EllipticalShape_t	 elliptical;
		ssem_RadialShape_t	 radial;
		ssem_RadialShapes_t	 radialShapes;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_Shape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_Shape;
extern asn_CHOICE_specifics_t asn_SPC_ssem_Shape_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_Shape_1[6];
extern asn_per_constraints_t asn_PER_type_ssem_Shape_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_Shape_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
