/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_GeoPosition_H_
#define	_ssem_GeoPosition_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_Latitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_Longitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_AltitudeValue.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_GeoPosition */
typedef struct ssem_GeoPosition {
	ssem_ETSI_ITS_CDD_Latitude_t	 latitude;
	ssem_ETSI_ITS_CDD_Longitude_t	 longitude;
	ssem_ETSI_ITS_CDD_AltitudeValue_t	*altitude;	/* DEFAULT 800001 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_GeoPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_GeoPosition;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_GeoPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_GeoPosition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_GeoPosition_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
