/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_InterferenceManagementZoneType_H_
#define	_ssem_InterferenceManagementZoneType_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_InterferenceManagementZoneType {
	ssem_InterferenceManagementZoneType_permanentCenDsrcTolling	= 0,
	ssem_InterferenceManagementZoneType_temporaryCenDsrcTolling	= 1,
	ssem_InterferenceManagementZoneType_unavailable	= 2,
	ssem_InterferenceManagementZoneType_urbanRail	= 3,
	ssem_InterferenceManagementZoneType_satelliteStation	= 4,
	ssem_InterferenceManagementZoneType_fixedLinks	= 5
	/*
	 * Enumeration is extensible
	 */
} e_ssem_InterferenceManagementZoneType;

/* ssem_InterferenceManagementZoneType */
typedef long	 ssem_InterferenceManagementZoneType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_InterferenceManagementZoneType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_InterferenceManagementZoneType;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_InterferenceManagementZoneType_specs_1;
asn_struct_free_f ssem_InterferenceManagementZoneType_free;
asn_struct_print_f ssem_InterferenceManagementZoneType_print;
asn_constr_check_f ssem_InterferenceManagementZoneType_constraint;
jer_type_encoder_f ssem_InterferenceManagementZoneType_encode_jer;
per_type_decoder_f ssem_InterferenceManagementZoneType_decode_uper;
per_type_encoder_f ssem_InterferenceManagementZoneType_encode_uper;
per_type_decoder_f ssem_InterferenceManagementZoneType_decode_aper;
per_type_encoder_f ssem_InterferenceManagementZoneType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_InterferenceManagementZoneType_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
