/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_LaneDataAttribute_H_
#define	_ssem_ts_LaneDataAttribute_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ts_DeltaAngle.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_RoadwayCrownAngle.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_MergeDivergeNodeAngle.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_SpeedLimitList.h"
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_LaneDataAttribute_PR {
	ssem_ts_LaneDataAttribute_PR_NOTHING,	/* No components present */
	ssem_ts_LaneDataAttribute_PR_pathEndPointAngle,
	ssem_ts_LaneDataAttribute_PR_laneCrownPointCenter,
	ssem_ts_LaneDataAttribute_PR_laneCrownPointLeft,
	ssem_ts_LaneDataAttribute_PR_laneCrownPointRight,
	ssem_ts_LaneDataAttribute_PR_laneAngle,
	ssem_ts_LaneDataAttribute_PR_speedLimits,
	ssem_ts_LaneDataAttribute_PR_regional
	/* Extensions may appear below */
	
} ssem_ts_LaneDataAttribute_PR;

/* Forward declarations */
struct ssem_ts_Reg_LaneDataAttribute;

/* ssem_ts_LaneDataAttribute */
typedef struct ssem_ts_LaneDataAttribute {
	ssem_ts_LaneDataAttribute_PR present;
	union ssem_ts_LaneDataAttribute_u {
		ssem_ts_DeltaAngle_t	 pathEndPointAngle;
		ssem_ts_RoadwayCrownAngle_t	 laneCrownPointCenter;
		ssem_ts_RoadwayCrownAngle_t	 laneCrownPointLeft;
		ssem_ts_RoadwayCrownAngle_t	 laneCrownPointRight;
		ssem_ts_MergeDivergeNodeAngle_t	 laneAngle;
		ssem_ts_SpeedLimitList_t	 speedLimits;
		struct ssem_ts_LaneDataAttribute__regional {
			A_SEQUENCE_OF(struct ssem_ts_Reg_LaneDataAttribute) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} regional;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ts_LaneDataAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_LaneDataAttribute;
extern asn_CHOICE_specifics_t asn_SPC_ssem_ts_LaneDataAttribute_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_ts_LaneDataAttribute_1[7];
extern asn_per_constraints_t asn_PER_type_ssem_ts_LaneDataAttribute_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_ts_RegionalExtension.h"

#endif	/* _ssem_ts_LaneDataAttribute_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
