/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ITS_Container_DangerousSituationSubCauseCode_H_
#define	_ssem_ITS_Container_DangerousSituationSubCauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ITS_Container_DangerousSituationSubCauseCode {
	ssem_ITS_Container_DangerousSituationSubCauseCode_unavailable	= 0,
	ssem_ITS_Container_DangerousSituationSubCauseCode_emergencyElectronicBrakeEngaged	= 1,
	ssem_ITS_Container_DangerousSituationSubCauseCode_preCrashSystemEngaged	= 2,
	ssem_ITS_Container_DangerousSituationSubCauseCode_espEngaged	= 3,
	ssem_ITS_Container_DangerousSituationSubCauseCode_absEngaged	= 4,
	ssem_ITS_Container_DangerousSituationSubCauseCode_aebEngaged	= 5,
	ssem_ITS_Container_DangerousSituationSubCauseCode_brakeWarningEngaged	= 6,
	ssem_ITS_Container_DangerousSituationSubCauseCode_collisionRiskWarningEngaged	= 7
} e_ssem_ITS_Container_DangerousSituationSubCauseCode;

/* ssem_ITS-Container_DangerousSituationSubCauseCode */
typedef long	 ssem_ITS_Container_DangerousSituationSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ITS_Container_DangerousSituationSubCauseCode;
asn_struct_free_f ssem_ITS_Container_DangerousSituationSubCauseCode_free;
asn_struct_print_f ssem_ITS_Container_DangerousSituationSubCauseCode_print;
asn_constr_check_f ssem_ITS_Container_DangerousSituationSubCauseCode_constraint;
jer_type_encoder_f ssem_ITS_Container_DangerousSituationSubCauseCode_encode_jer;
per_type_decoder_f ssem_ITS_Container_DangerousSituationSubCauseCode_decode_uper;
per_type_encoder_f ssem_ITS_Container_DangerousSituationSubCauseCode_encode_uper;
per_type_decoder_f ssem_ITS_Container_DangerousSituationSubCauseCode_decode_aper;
per_type_encoder_f ssem_ITS_Container_DangerousSituationSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ITS_Container_DangerousSituationSubCauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
