/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_CartesianCoordinate_H_
#define	_ssem_CartesianCoordinate_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_CartesianCoordinate {
	ssem_CartesianCoordinate_negativeOutOfRange	= -32768,
	ssem_CartesianCoordinate_positiveOutOfRange	= 32767
} e_ssem_CartesianCoordinate;

/* ssem_CartesianCoordinate */
typedef long	 ssem_CartesianCoordinate_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_CartesianCoordinate_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_CartesianCoordinate;
asn_struct_free_f ssem_CartesianCoordinate_free;
asn_struct_print_f ssem_CartesianCoordinate_print;
asn_constr_check_f ssem_CartesianCoordinate_constraint;
jer_type_encoder_f ssem_CartesianCoordinate_encode_jer;
per_type_decoder_f ssem_CartesianCoordinate_decode_uper;
per_type_encoder_f ssem_CartesianCoordinate_encode_uper;
per_type_decoder_f ssem_CartesianCoordinate_decode_aper;
per_type_encoder_f ssem_CartesianCoordinate_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_CartesianCoordinate_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
