/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_LaneType_H_
#define	_ssem_LaneType_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_LaneType {
	ssem_LaneType_traffic	= 0,
	ssem_LaneType_through	= 1,
	ssem_LaneType_reversible	= 2,
	ssem_LaneType_acceleration	= 3,
	ssem_LaneType_deceleration	= 4,
	ssem_LaneType_leftHandTurning	= 5,
	ssem_LaneType_rightHandTurning	= 6,
	ssem_LaneType_dedicatedVehicle	= 7,
	ssem_LaneType_bus	= 8,
	ssem_LaneType_taxi	= 9,
	ssem_LaneType_hov	= 10,
	ssem_LaneType_hot	= 11,
	ssem_LaneType_pedestrian	= 12,
	ssem_LaneType_cycleLane	= 13,
	ssem_LaneType_median	= 14,
	ssem_LaneType_striping	= 15,
	ssem_LaneType_trackedVehicle	= 16,
	ssem_LaneType_parking	= 17,
	ssem_LaneType_emergency	= 18,
	ssem_LaneType_verge	= 19,
	ssem_LaneType_minimumRiskManoeuvre	= 20,
	ssem_LaneType_exclusiveCycleLane	= 21,
	ssem_LaneType_unknown	= 31
} e_ssem_LaneType;

/* ssem_LaneType */
typedef long	 ssem_LaneType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_LaneType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_LaneType;
asn_struct_free_f ssem_LaneType_free;
asn_struct_print_f ssem_LaneType_print;
asn_constr_check_f ssem_LaneType_constraint;
jer_type_encoder_f ssem_LaneType_encode_jer;
per_type_decoder_f ssem_LaneType_decode_uper;
per_type_encoder_f ssem_LaneType_encode_uper;
per_type_decoder_f ssem_LaneType_decode_aper;
per_type_encoder_f ssem_LaneType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_LaneType_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
