/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_PositionConfidenceSet_H_
#define	_ssem_DSRC_PositionConfidenceSet_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_PositionConfidence.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_ElevationConfidence.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_DSRC_PositionConfidenceSet */
typedef struct ssem_DSRC_PositionConfidenceSet {
	ssem_DSRC_PositionConfidence_t	 pos;
	ssem_DSRC_ElevationConfidence_t	 elevation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_DSRC_PositionConfidenceSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_PositionConfidenceSet;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_DSRC_PositionConfidenceSet_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_DSRC_PositionConfidenceSet_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_DSRC_PositionConfidenceSet_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
