/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_H_
#define	_ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode {
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_unavailable	= 0,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_emergencyElectronicBrakeEngaged	= 1,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_preCrashSystemEngaged	= 2,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_espEngaged	= 3,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_absEngaged	= 4,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_aebEngaged	= 5,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_brakeWarningEngaged	= 6,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_collisionRiskWarningEngaged	= 7,
	ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_riskMitigationFunctionEngaged	= 8
} e_ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode;

/* ssem_ETSI-ITS-CDD_DangerousSituationSubCauseCode */
typedef long	 ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode;
asn_struct_free_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_free;
asn_struct_print_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_print;
asn_constr_check_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_constraint;
jer_type_encoder_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_CDD_DangerousSituationSubCauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
