/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_AccessTechnologyClass_H_
#define	_ssem_AccessTechnologyClass_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_AccessTechnologyClass {
	ssem_AccessTechnologyClass_any	= 0,
	ssem_AccessTechnologyClass_itsg5Class	= 1,
	ssem_AccessTechnologyClass_ltev2xClass	= 2,
	ssem_AccessTechnologyClass_nrv2xClass	= 3
	/*
	 * Enumeration is extensible
	 */
} e_ssem_AccessTechnologyClass;

/* ssem_AccessTechnologyClass */
typedef long	 ssem_AccessTechnologyClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_AccessTechnologyClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_AccessTechnologyClass;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_AccessTechnologyClass_specs_1;
asn_struct_free_f ssem_AccessTechnologyClass_free;
asn_struct_print_f ssem_AccessTechnologyClass_print;
asn_constr_check_f ssem_AccessTechnologyClass_constraint;
jer_type_encoder_f ssem_AccessTechnologyClass_encode_jer;
per_type_decoder_f ssem_AccessTechnologyClass_decode_uper;
per_type_encoder_f ssem_AccessTechnologyClass_encode_uper;
per_type_decoder_f ssem_AccessTechnologyClass_decode_aper;
per_type_encoder_f ssem_AccessTechnologyClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_AccessTechnologyClass_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
