/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_VruSizeClass_H_
#define	_ssem_VruSizeClass_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_VruSizeClass {
	ssem_VruSizeClass_unavailable	= 0,
	ssem_VruSizeClass_low	= 1,
	ssem_VruSizeClass_medium	= 2,
	ssem_VruSizeClass_high	= 3
} e_ssem_VruSizeClass;

/* ssem_VruSizeClass */
typedef long	 ssem_VruSizeClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_VruSizeClass;
asn_struct_free_f ssem_VruSizeClass_free;
asn_struct_print_f ssem_VruSizeClass_print;
asn_constr_check_f ssem_VruSizeClass_constraint;
jer_type_encoder_f ssem_VruSizeClass_encode_jer;
per_type_decoder_f ssem_VruSizeClass_decode_uper;
per_type_encoder_f ssem_VruSizeClass_encode_uper;
per_type_decoder_f ssem_VruSizeClass_decode_aper;
per_type_encoder_f ssem_VruSizeClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_VruSizeClass_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
