/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_VehicleRole_H_
#define	_ssem_ts_VehicleRole_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_VehicleRole {
	ssem_ts_VehicleRole_default	= 0,
	ssem_ts_VehicleRole_publicTransport	= 1,
	ssem_ts_VehicleRole_specialTransport	= 2,
	ssem_ts_VehicleRole_dangerousGoods	= 3,
	ssem_ts_VehicleRole_roadWork	= 4,
	ssem_ts_VehicleRole_rescue	= 5,
	ssem_ts_VehicleRole_emergency	= 6,
	ssem_ts_VehicleRole_safetyCar	= 7,
	ssem_ts_VehicleRole_agriculture	= 8,
	ssem_ts_VehicleRole_commercial	= 9,
	ssem_ts_VehicleRole_military	= 10,
	ssem_ts_VehicleRole_roadOperator	= 11,
	ssem_ts_VehicleRole_taxi	= 12,
	ssem_ts_VehicleRole_reserved1	= 13,
	ssem_ts_VehicleRole_reserved2	= 14,
	ssem_ts_VehicleRole_reserved3	= 15
} e_ssem_ts_VehicleRole;

/* ssem_ts_VehicleRole */
typedef long	 ssem_ts_VehicleRole_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_VehicleRole;
asn_struct_free_f ssem_ts_VehicleRole_free;
asn_struct_print_f ssem_ts_VehicleRole_print;
asn_constr_check_f ssem_ts_VehicleRole_constraint;
jer_type_encoder_f ssem_ts_VehicleRole_encode_jer;
per_type_decoder_f ssem_ts_VehicleRole_decode_uper;
per_type_encoder_f ssem_ts_VehicleRole_encode_uper;
per_type_decoder_f ssem_ts_VehicleRole_decode_aper;
per_type_encoder_f ssem_ts_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ts_VehicleRole_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
