/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_PathPointPredicted_H_
#define	_ssem_PathPointPredicted_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_DeltaLatitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_DeltaLongitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_DeltaAltitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_AltitudeConfidence.h"
#include "etsi_its_ssem_ts_coding/ssem_StandardLength9b.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_PosConfidenceEllipse;
struct ssem_PathDeltaTimeChoice;

/* ssem_PathPointPredicted */
typedef struct ssem_PathPointPredicted {
	ssem_ETSI_ITS_CDD_DeltaLatitude_t	 deltaLatitude;
	ssem_ETSI_ITS_CDD_DeltaLongitude_t	 deltaLongitude;
	struct ssem_PosConfidenceEllipse	*horizontalPositionConfidence;	/* OPTIONAL */
	ssem_ETSI_ITS_CDD_DeltaAltitude_t	*deltaAltitude;	/* DEFAULT 12800 */
	ssem_ETSI_ITS_CDD_AltitudeConfidence_t	*altitudeConfidence;	/* DEFAULT 15 */
	struct ssem_PathDeltaTimeChoice	*pathDeltaTime;	/* OPTIONAL */
	ssem_StandardLength9b_t	*symmetricAreaOffset;	/* OPTIONAL */
	ssem_StandardLength9b_t	*asymmetricAreaOffset;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_PathPointPredicted_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_PathPointPredicted;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_PathPointPredicted_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_PathPointPredicted_1[8];
extern asn_per_constraints_t asn_PER_type_ssem_PathPointPredicted_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_PosConfidenceEllipse.h"
#include "etsi_its_ssem_ts_coding/ssem_PathDeltaTimeChoice.h"

#endif	/* _ssem_PathPointPredicted_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
