/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_AxlesCount_H_
#define	_ssem_AxlesCount_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_AxlesCount {
	ssem_AxlesCount_outOfRange	= 1001,
	ssem_AxlesCount_unavailable	= 1002
} e_ssem_AxlesCount;

/* ssem_AxlesCount */
typedef long	 ssem_AxlesCount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_AxlesCount;
asn_struct_free_f ssem_AxlesCount_free;
asn_struct_print_f ssem_AxlesCount_print;
asn_constr_check_f ssem_AxlesCount_constraint;
jer_type_encoder_f ssem_AxlesCount_encode_jer;
per_type_decoder_f ssem_AxlesCount_decode_uper;
per_type_encoder_f ssem_AxlesCount_encode_uper;
per_type_decoder_f ssem_AxlesCount_decode_aper;
per_type_encoder_f ssem_AxlesCount_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_AxlesCount_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
