/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ITS_Container_ItsPduHeader_H_
#define	_ssem_ITS_Container_ItsPduHeader_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>
#include "etsi_its_ssem_ts_coding/ssem_ITS-Container_StationID.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ITS_Container_ItsPduHeader__messageID {
	ssem_ITS_Container_ItsPduHeader__messageID_denm	= 1,
	ssem_ITS_Container_ItsPduHeader__messageID_cam	= 2,
	ssem_ITS_Container_ItsPduHeader__messageID_poi	= 3,
	ssem_ITS_Container_ItsPduHeader__messageID_spatem	= 4,
	ssem_ITS_Container_ItsPduHeader__messageID_mapem	= 5,
	ssem_ITS_Container_ItsPduHeader__messageID_ivim	= 6,
	ssem_ITS_Container_ItsPduHeader__messageID_ev_rsr	= 7,
	ssem_ITS_Container_ItsPduHeader__messageID_tistpgtransaction	= 8,
	ssem_ITS_Container_ItsPduHeader__messageID_srem	= 9,
	ssem_ITS_Container_ItsPduHeader__messageID_ssem	= 10,
	ssem_ITS_Container_ItsPduHeader__messageID_evcsn	= 11,
	ssem_ITS_Container_ItsPduHeader__messageID_saem	= 12,
	ssem_ITS_Container_ItsPduHeader__messageID_rtcmem	= 13
} e_ssem_ITS_Container_ItsPduHeader__messageID;

/* ssem_ITS-Container_ItsPduHeader */
typedef struct ssem_ITS_Container_ItsPduHeader {
	long	 protocolVersion;
	long	 messageID;
	ssem_ITS_Container_StationID_t	 stationID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ITS_Container_ItsPduHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ITS_Container_ItsPduHeader;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ITS_Container_ItsPduHeader_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
