/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_BasicVehicleRole_H_
#define	_ssem_ETSI_ITS_DSRC_BasicVehicleRole_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_DSRC_BasicVehicleRole {
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_basicVehicle	= 0,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_publicTransport	= 1,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_specialTransport	= 2,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_dangerousGoods	= 3,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_roadWork	= 4,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_roadRescue	= 5,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_emergency	= 6,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_safetyCar	= 7,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_none_unknown	= 8,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_truck	= 9,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_motorcycle	= 10,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_roadSideSource	= 11,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_police	= 12,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_fire	= 13,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_ambulance	= 14,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_dot	= 15,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_transit	= 16,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_slowMoving	= 17,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_stopNgo	= 18,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_cyclist	= 19,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_pedestrian	= 20,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_nonMotorized	= 21,
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_military	= 22,
	/*
	 * Enumeration is extensible
	 */
	ssem_ETSI_ITS_DSRC_BasicVehicleRole_tram	= 23
} e_ssem_ETSI_ITS_DSRC_BasicVehicleRole;

/* ssem_ETSI-ITS-DSRC_BasicVehicleRole */
typedef long	 ssem_ETSI_ITS_DSRC_BasicVehicleRole_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_BasicVehicleRole_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_BasicVehicleRole;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_ETSI_ITS_DSRC_BasicVehicleRole_specs_1;
asn_struct_free_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_free;
asn_struct_print_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_print;
asn_constr_check_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_constraint;
jer_type_encoder_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_BasicVehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_DSRC_BasicVehicleRole_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
