/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_FuelType_H_
#define	_ssem_DSRC_FuelType_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_DSRC_FuelType */
typedef long	 ssem_DSRC_FuelType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_DSRC_FuelType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_FuelType;
asn_struct_free_f ssem_DSRC_FuelType_free;
asn_struct_print_f ssem_DSRC_FuelType_print;
asn_constr_check_f ssem_DSRC_FuelType_constraint;
jer_type_encoder_f ssem_DSRC_FuelType_encode_jer;
per_type_decoder_f ssem_DSRC_FuelType_decode_uper;
per_type_encoder_f ssem_DSRC_FuelType_encode_uper;
per_type_decoder_f ssem_DSRC_FuelType_decode_aper;
per_type_encoder_f ssem_DSRC_FuelType_encode_aper;
#define ssem_DSRC_FuelType_DSRC_unknownFuel	((ssem_DSRC_FuelType_t)0)
#define ssem_DSRC_FuelType_DSRC_gasoline	((ssem_DSRC_FuelType_t)1)
#define ssem_DSRC_FuelType_DSRC_ethanol	((ssem_DSRC_FuelType_t)2)
#define ssem_DSRC_FuelType_DSRC_diesel	((ssem_DSRC_FuelType_t)3)
#define ssem_DSRC_FuelType_DSRC_electric	((ssem_DSRC_FuelType_t)4)
#define ssem_DSRC_FuelType_DSRC_hybrid	((ssem_DSRC_FuelType_t)5)
#define ssem_DSRC_FuelType_DSRC_hydrogen	((ssem_DSRC_FuelType_t)6)
#define ssem_DSRC_FuelType_DSRC_natGasLiquid	((ssem_DSRC_FuelType_t)7)
#define ssem_DSRC_FuelType_DSRC_natGasComp	((ssem_DSRC_FuelType_t)8)
#define ssem_DSRC_FuelType_DSRC_propane	((ssem_DSRC_FuelType_t)9)

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_DSRC_FuelType_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
