/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018-patched.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_ComputedLane_H_
#define	_ssem_ts_ComputedLane_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ts_LaneID.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_Angle.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_Scale-B12.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_DrivenLineOffsetSm.h"
#include "etsi_its_ssem_ts_coding/ssem_ts_DrivenLineOffsetLg.h"
#include <etsi_its_ssem_ts_coding/constr_CHOICE.h>
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_ComputedLane__offsetXaxis_PR {
	ssem_ts_ComputedLane__offsetXaxis_PR_NOTHING,	/* No components present */
	ssem_ts_ComputedLane__offsetXaxis_PR_small,
	ssem_ts_ComputedLane__offsetXaxis_PR_large
} ssem_ts_ComputedLane__offsetXaxis_PR;
typedef enum ssem_ts_ComputedLane__offsetYaxis_PR {
	ssem_ts_ComputedLane__offsetYaxis_PR_NOTHING,	/* No components present */
	ssem_ts_ComputedLane__offsetYaxis_PR_small,
	ssem_ts_ComputedLane__offsetYaxis_PR_large
} ssem_ts_ComputedLane__offsetYaxis_PR;

/* Forward declarations */
struct ssem_ts_Reg_ComputedLane;

/* ssem_ts_ComputedLane */
typedef struct ssem_ts_ComputedLane {
	ssem_ts_LaneID_t	 referenceLaneId;
	struct ssem_ts_ComputedLane__offsetXaxis {
		ssem_ts_ComputedLane__offsetXaxis_PR present;
		union ssem_ts_ComputedLane__ssem_ts_offsetXaxis_u {
			ssem_ts_DrivenLineOffsetSm_t	 small;
			ssem_ts_DrivenLineOffsetLg_t	 large;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offsetXaxis;
	struct ssem_ts_ComputedLane__offsetYaxis {
		ssem_ts_ComputedLane__offsetYaxis_PR present;
		union ssem_ts_ComputedLane__ssem_ts_offsetYaxis_u {
			ssem_ts_DrivenLineOffsetSm_t	 small;
			ssem_ts_DrivenLineOffsetLg_t	 large;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offsetYaxis;
	ssem_ts_Angle_t	*rotateXY;	/* OPTIONAL */
	ssem_ts_Scale_B12_t	*scaleXaxis;	/* OPTIONAL */
	ssem_ts_Scale_B12_t	*scaleYaxis;	/* OPTIONAL */
	struct ssem_ts_ComputedLane__regional {
		A_SEQUENCE_OF(struct ssem_ts_Reg_ComputedLane) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ts_ComputedLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_ComputedLane;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_ts_ComputedLane_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_ts_ComputedLane_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_ts_RegionalExtension.h"

#endif	/* _ssem_ts_ComputedLane_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
