/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_TourNumber_H_
#define	_ssem_TourNumber_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_TourNumber */
typedef unsigned long	 ssem_TourNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_TourNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_TourNumber;
extern const asn_INTEGER_specifics_t asn_SPC_ssem_TourNumber_specs_1;
asn_struct_free_f ssem_TourNumber_free;
asn_struct_print_f ssem_TourNumber_print;
asn_constr_check_f ssem_TourNumber_constraint;
jer_type_encoder_f ssem_TourNumber_encode_jer;
per_type_decoder_f ssem_TourNumber_decode_uper;
per_type_encoder_f ssem_TourNumber_encode_uper;
per_type_decoder_f ssem_TourNumber_decode_aper;
per_type_encoder_f ssem_TourNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_TourNumber_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
