/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_GNSSstatus_H_
#define	_ssem_ETSI_ITS_DSRC_GNSSstatus_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_DSRC_GNSSstatus {
	ssem_ETSI_ITS_DSRC_GNSSstatus_unavailable	= 0,
	ssem_ETSI_ITS_DSRC_GNSSstatus_isHealthy	= 1,
	ssem_ETSI_ITS_DSRC_GNSSstatus_isMonitored	= 2,
	ssem_ETSI_ITS_DSRC_GNSSstatus_baseStationType	= 3,
	ssem_ETSI_ITS_DSRC_GNSSstatus_aPDOPofUnder5	= 4,
	ssem_ETSI_ITS_DSRC_GNSSstatus_inViewOfUnder5	= 5,
	ssem_ETSI_ITS_DSRC_GNSSstatus_localCorrectionsPresent	= 6,
	ssem_ETSI_ITS_DSRC_GNSSstatus_networkCorrectionsPresent	= 7
} e_ssem_ETSI_ITS_DSRC_GNSSstatus;

/* ssem_ETSI-ITS-DSRC_GNSSstatus */
typedef BIT_STRING_t	 ssem_ETSI_ITS_DSRC_GNSSstatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_GNSSstatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_GNSSstatus;
asn_struct_free_f ssem_ETSI_ITS_DSRC_GNSSstatus_free;
asn_struct_print_f ssem_ETSI_ITS_DSRC_GNSSstatus_print;
asn_constr_check_f ssem_ETSI_ITS_DSRC_GNSSstatus_constraint;
jer_type_encoder_f ssem_ETSI_ITS_DSRC_GNSSstatus_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_DSRC_GNSSstatus_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_GNSSstatus_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_DSRC_GNSSstatus_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_GNSSstatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_DSRC_GNSSstatus_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
