/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_SensorTypes_H_
#define	_ssem_SensorTypes_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_SensorTypes {
	ssem_SensorTypes_undefined	= 0,
	ssem_SensorTypes_radar	= 1,
	ssem_SensorTypes_lidar	= 2,
	ssem_SensorTypes_monovideo	= 3,
	ssem_SensorTypes_stereovision	= 4,
	ssem_SensorTypes_nightvision	= 5,
	ssem_SensorTypes_ultrasonic	= 6,
	ssem_SensorTypes_pmd	= 7,
	ssem_SensorTypes_inductionLoop	= 8,
	ssem_SensorTypes_sphericalCamera	= 9,
	ssem_SensorTypes_uwb	= 10,
	ssem_SensorTypes_acoustic	= 11,
	ssem_SensorTypes_localAggregation	= 12,
	ssem_SensorTypes_itsAggregation	= 13,
	ssem_SensorTypes_rfid	= 14
} e_ssem_SensorTypes;

/* ssem_SensorTypes */
typedef BIT_STRING_t	 ssem_SensorTypes_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_SensorTypes_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_SensorTypes;
asn_struct_free_f ssem_SensorTypes_free;
asn_struct_print_f ssem_SensorTypes_print;
asn_constr_check_f ssem_SensorTypes_constraint;
jer_type_encoder_f ssem_SensorTypes_encode_jer;
per_type_decoder_f ssem_SensorTypes_decode_uper;
per_type_encoder_f ssem_SensorTypes_encode_uper;
per_type_decoder_f ssem_SensorTypes_decode_aper;
per_type_encoder_f ssem_SensorTypes_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_SensorTypes_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
