/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ts_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ts_LateralAccelerationValue_H_
#define	_ssem_ts_LateralAccelerationValue_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ts_LateralAccelerationValue {
	ssem_ts_LateralAccelerationValue_pointOneMeterPerSecSquaredToRight	= -1,
	ssem_ts_LateralAccelerationValue_pointOneMeterPerSecSquaredToLeft	= 1,
	ssem_ts_LateralAccelerationValue_unavailable	= 161
} e_ssem_ts_LateralAccelerationValue;

/* ssem_ts_LateralAccelerationValue */
typedef long	 ssem_ts_LateralAccelerationValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ts_LateralAccelerationValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ts_LateralAccelerationValue;
asn_struct_free_f ssem_ts_LateralAccelerationValue_free;
asn_struct_print_f ssem_ts_LateralAccelerationValue_print;
asn_constr_check_f ssem_ts_LateralAccelerationValue_constraint;
jer_type_encoder_f ssem_ts_LateralAccelerationValue_encode_jer;
per_type_decoder_f ssem_ts_LateralAccelerationValue_decode_uper;
per_type_encoder_f ssem_ts_LateralAccelerationValue_encode_uper;
per_type_decoder_f ssem_ts_LateralAccelerationValue_decode_aper;
per_type_encoder_f ssem_ts_LateralAccelerationValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ts_LateralAccelerationValue_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
