/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_Ext2_H_
#define	_ssem_Ext2_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>
#include "etsi_its_ssem_ts_coding/ssem_Ext3.h"
#include <etsi_its_ssem_ts_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_Ext2_PR {
	ssem_Ext2_PR_NOTHING,	/* No components present */
	ssem_Ext2_PR_content,
	ssem_Ext2_PR_extension
} ssem_Ext2_PR;

/* ssem_Ext2 */
typedef struct ssem_Ext2 {
	ssem_Ext2_PR present;
	union ssem_Ext2_u {
		long	 content;
		ssem_Ext3_t	 extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_Ext2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_Ext2;
extern asn_CHOICE_specifics_t asn_SPC_ssem_Ext2_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_Ext2_1[2];
extern asn_per_constraints_t asn_PER_type_ssem_Ext2_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_Ext2_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
