/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ITS_Container_CauseCode_H_
#define	_ssem_ITS_Container_CauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ITS-Container_CauseCodeType.h"
#include "etsi_its_ssem_ts_coding/ssem_ITS-Container_SubCauseCodeType.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_ITS-Container_CauseCode */
typedef struct ssem_ITS_Container_CauseCode {
	ssem_ITS_Container_CauseCodeType_t	 causeCode;
	ssem_ITS_Container_SubCauseCodeType_t	 subCauseCode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ITS_Container_CauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ITS_Container_CauseCode;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ITS_Container_CauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
