/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_AccelerationMagnitudeValue_H_
#define	_ssem_AccelerationMagnitudeValue_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_AccelerationMagnitudeValue {
	ssem_AccelerationMagnitudeValue_positiveOutOfRange	= 160,
	ssem_AccelerationMagnitudeValue_unavailable	= 161
} e_ssem_AccelerationMagnitudeValue;

/* ssem_AccelerationMagnitudeValue */
typedef long	 ssem_AccelerationMagnitudeValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_AccelerationMagnitudeValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_AccelerationMagnitudeValue;
asn_struct_free_f ssem_AccelerationMagnitudeValue_free;
asn_struct_print_f ssem_AccelerationMagnitudeValue_print;
asn_constr_check_f ssem_AccelerationMagnitudeValue_constraint;
jer_type_encoder_f ssem_AccelerationMagnitudeValue_encode_jer;
per_type_decoder_f ssem_AccelerationMagnitudeValue_decode_uper;
per_type_encoder_f ssem_AccelerationMagnitudeValue_encode_uper;
per_type_decoder_f ssem_AccelerationMagnitudeValue_decode_aper;
per_type_encoder_f ssem_AccelerationMagnitudeValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_AccelerationMagnitudeValue_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
