/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-DSRC"
 * 	found in "/input/DSRC.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_DSRC_LaneSharing_H_
#define	_ssem_ETSI_ITS_DSRC_LaneSharing_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ETSI_ITS_DSRC_LaneSharing {
	ssem_ETSI_ITS_DSRC_LaneSharing_overlappingLaneDescriptionProvided	= 0,
	ssem_ETSI_ITS_DSRC_LaneSharing_multipleLanesTreatedAsOneLane	= 1,
	ssem_ETSI_ITS_DSRC_LaneSharing_otherNonMotorizedTrafficTypes	= 2,
	ssem_ETSI_ITS_DSRC_LaneSharing_individualMotorizedVehicleTraffic	= 3,
	ssem_ETSI_ITS_DSRC_LaneSharing_busVehicleTraffic	= 4,
	ssem_ETSI_ITS_DSRC_LaneSharing_taxiVehicleTraffic	= 5,
	ssem_ETSI_ITS_DSRC_LaneSharing_pedestriansTraffic	= 6,
	ssem_ETSI_ITS_DSRC_LaneSharing_cyclistVehicleTraffic	= 7,
	ssem_ETSI_ITS_DSRC_LaneSharing_trackedVehicleTraffic	= 8,
	ssem_ETSI_ITS_DSRC_LaneSharing_pedestrianTraffic	= 9
} e_ssem_ETSI_ITS_DSRC_LaneSharing;

/* ssem_ETSI-ITS-DSRC_LaneSharing */
typedef BIT_STRING_t	 ssem_ETSI_ITS_DSRC_LaneSharing_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ETSI_ITS_DSRC_LaneSharing_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_DSRC_LaneSharing;
asn_struct_free_f ssem_ETSI_ITS_DSRC_LaneSharing_free;
asn_struct_print_f ssem_ETSI_ITS_DSRC_LaneSharing_print;
asn_constr_check_f ssem_ETSI_ITS_DSRC_LaneSharing_constraint;
jer_type_encoder_f ssem_ETSI_ITS_DSRC_LaneSharing_encode_jer;
per_type_decoder_f ssem_ETSI_ITS_DSRC_LaneSharing_decode_uper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_LaneSharing_encode_uper;
per_type_decoder_f ssem_ETSI_ITS_DSRC_LaneSharing_decode_aper;
per_type_encoder_f ssem_ETSI_ITS_DSRC_LaneSharing_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_DSRC_LaneSharing_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
