/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_VehicleMovementControl_H_
#define	_ssem_VehicleMovementControl_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_PedalStatus.h"
#include "etsi_its_ssem_ts_coding/ssem_SaeAutomationLevel.h"
#include "etsi_its_ssem_ts_coding/ssem_AutomationControl.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_AccelerationControl.h"
#include "etsi_its_ssem_ts_coding/ssem_AccelerationControlExtension.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_VehicleMovementControl */
typedef struct ssem_VehicleMovementControl {
	ssem_PedalStatus_t	 accelerationPedalStatus;
	ssem_PedalStatus_t	 brakePedalStatus;
	ssem_SaeAutomationLevel_t	*saeAutomationLevel;	/* OPTIONAL */
	ssem_AutomationControl_t	*automationControl;	/* OPTIONAL */
	ssem_ETSI_ITS_CDD_AccelerationControl_t	*accelerationControl;	/* OPTIONAL */
	ssem_AccelerationControlExtension_t	*accelerationControlExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_VehicleMovementControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_VehicleMovementControl;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_VehicleMovementControl_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
