/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_CDD_CenDsrcTollingZone_H_
#define	_ssem_ETSI_ITS_CDD_CenDsrcTollingZone_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_Latitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_Longitude.h"
#include "etsi_its_ssem_ts_coding/ssem_ProtectedZoneId.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_ETSI-ITS-CDD_CenDsrcTollingZone */
typedef struct ssem_ETSI_ITS_CDD_CenDsrcTollingZone {
	ssem_ETSI_ITS_CDD_Latitude_t	 protectedZoneLatitude;
	ssem_ETSI_ITS_CDD_Longitude_t	 protectedZoneLongitude;
	ssem_ProtectedZoneId_t	*cenDsrcTollingZoneId;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ETSI_ITS_CDD_CenDsrcTollingZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_CDD_CenDsrcTollingZone;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_CDD_CenDsrcTollingZone_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
