/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ETSI_ITS_CDD_VerticalAcceleration_H_
#define	_ssem_ETSI_ITS_CDD_VerticalAcceleration_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_VerticalAccelerationValue.h"
#include "etsi_its_ssem_ts_coding/ssem_ETSI-ITS-CDD_AccelerationConfidence.h"
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ssem_ETSI-ITS-CDD_VerticalAcceleration */
typedef struct ssem_ETSI_ITS_CDD_VerticalAcceleration {
	ssem_ETSI_ITS_CDD_VerticalAccelerationValue_t	 verticalAccelerationValue;
	ssem_ETSI_ITS_CDD_AccelerationConfidence_t	 verticalAccelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_ETSI_ITS_CDD_VerticalAcceleration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_ETSI_ITS_CDD_VerticalAcceleration;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ETSI_ITS_CDD_VerticalAcceleration_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
