/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_ImpassabilitySubCauseCode_H_
#define	_ssem_ImpassabilitySubCauseCode_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ssem_ImpassabilitySubCauseCode {
	ssem_ImpassabilitySubCauseCode_unavailable	= 0,
	ssem_ImpassabilitySubCauseCode_flooding	= 1,
	ssem_ImpassabilitySubCauseCode_dangerOfAvalanches	= 2,
	ssem_ImpassabilitySubCauseCode_blastingOfAvalanches	= 3,
	ssem_ImpassabilitySubCauseCode_landslips	= 4,
	ssem_ImpassabilitySubCauseCode_chemicalSpillage	= 5,
	ssem_ImpassabilitySubCauseCode_winterClosure	= 6,
	ssem_ImpassabilitySubCauseCode_sinkhole	= 7,
	ssem_ImpassabilitySubCauseCode_earthquakeDamage	= 8,
	ssem_ImpassabilitySubCauseCode_fallenTrees	= 9,
	ssem_ImpassabilitySubCauseCode_rockfalls	= 10,
	ssem_ImpassabilitySubCauseCode_sewerOverflow	= 11,
	ssem_ImpassabilitySubCauseCode_stormDamage	= 12,
	ssem_ImpassabilitySubCauseCode_subsidence	= 13,
	ssem_ImpassabilitySubCauseCode_burstPipe	= 14,
	ssem_ImpassabilitySubCauseCode_burstWaterMain	= 15,
	ssem_ImpassabilitySubCauseCode_fallenPowerCables	= 16,
	ssem_ImpassabilitySubCauseCode_snowDrifts	= 17
} e_ssem_ImpassabilitySubCauseCode;

/* ssem_ImpassabilitySubCauseCode */
typedef long	 ssem_ImpassabilitySubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ssem_ImpassabilitySubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ssem_ImpassabilitySubCauseCode;
asn_struct_free_f ssem_ImpassabilitySubCauseCode_free;
asn_struct_print_f ssem_ImpassabilitySubCauseCode_print;
asn_constr_check_f ssem_ImpassabilitySubCauseCode_constraint;
jer_type_encoder_f ssem_ImpassabilitySubCauseCode_encode_jer;
per_type_decoder_f ssem_ImpassabilitySubCauseCode_decode_uper;
per_type_encoder_f ssem_ImpassabilitySubCauseCode_encode_uper;
per_type_decoder_f ssem_ImpassabilitySubCauseCode_decode_aper;
per_type_encoder_f ssem_ImpassabilitySubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ssem_ImpassabilitySubCauseCode_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
