/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/input/ETSI-ITS-CDD.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_IvimReferences_H_
#define	_ssem_IvimReferences_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_IvimReference;

/* ssem_IvimReferences */
typedef struct ssem_IvimReferences {
	A_SEQUENCE_OF(struct ssem_IvimReference) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_IvimReferences_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_IvimReferences;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_IvimReference.h"

#endif	/* _ssem_IvimReferences_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
