/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/ISO-TS-19091-addgrp-C-2018.asn"
 * 	`asn1c -fcompound-names -fprefix=ssem_ -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-example -gen-UPER -gen-JER`
 */

#ifndef	_ssem_DSRC_RequestorDescription_H_
#define	_ssem_DSRC_RequestorDescription_H_


#include <etsi_its_ssem_ts_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_VehicleID.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_DescriptiveName.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_TransitVehicleStatus.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_TransitVehicleOccupancy.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_DeltaTime.h"
#include <etsi_its_ssem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_ssem_ts_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ssem_RequestorType;
struct ssem_RequestorPositionVector;
struct ssem_Reg_RequestorDescription;

/* ssem_DSRC_RequestorDescription */
typedef struct ssem_DSRC_RequestorDescription {
	ssem_DSRC_VehicleID_t	 id;
	struct ssem_RequestorType	*type;	/* OPTIONAL */
	struct ssem_RequestorPositionVector	*position;	/* OPTIONAL */
	ssem_DSRC_DescriptiveName_t	*name;	/* OPTIONAL */
	ssem_DSRC_DescriptiveName_t	*routeName;	/* OPTIONAL */
	ssem_DSRC_TransitVehicleStatus_t	*transitStatus;	/* OPTIONAL */
	ssem_DSRC_TransitVehicleOccupancy_t	*transitOccupancy;	/* OPTIONAL */
	ssem_DSRC_DeltaTime_t	*transitSchedule;	/* OPTIONAL */
	struct ssem_DSRC_RequestorDescription__regional {
		A_SEQUENCE_OF(struct ssem_Reg_RequestorDescription) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ssem_DSRC_RequestorDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ssem_DSRC_RequestorDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_ssem_DSRC_RequestorDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_ssem_DSRC_RequestorDescription_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_ssem_ts_coding/ssem_DSRC_RequestorType.h"
#include "etsi_its_ssem_ts_coding/ssem_DSRC_RequestorPositionVector.h"
#include "etsi_its_ssem_ts_coding/ssem_RegionalExtension.h"

#endif	/* _ssem_DSRC_RequestorDescription_H_ */
#include <etsi_its_ssem_ts_coding/asn_internal.h>
