/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/SREM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  -o \
  etsi_its_conversion/etsi_its_srem_ts_conversion/include/etsi_its_srem_ts_conversion \
  -t \
  srem_ts
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
SignalHeadLocationList ::=	SEQUENCE (SIZE(1..64)) OF	SignalHeadLocation
----------------------------------------------------------------------------- */

#pragma once

#include <stdexcept>

#include <etsi_its_srem_ts_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_srem_ts_coding/srem_ts_SignalHeadLocationList.h>
#include <etsi_its_srem_ts_coding/srem_ts_SignalHeadLocation.h>
#include <etsi_its_srem_ts_conversion/convertSignalHeadLocation.h>
#include <etsi_its_srem_ts_msgs/msg/signal_head_location.hpp>
#include <etsi_its_srem_ts_msgs/msg/signal_head_location_list.hpp>
namespace srem_ts_msgs = etsi_its_srem_ts_msgs::msg;


namespace etsi_its_srem_ts_conversion {

void toRos_SignalHeadLocationList(const srem_ts_SignalHeadLocationList_t& in, srem_ts_msgs::SignalHeadLocationList& out) {
  for (int i = 0; i < in.list.count; ++i) {
    srem_ts_msgs::SignalHeadLocation el;
    toRos_SignalHeadLocation(*(in.list.array[i]), el);
    out.array.push_back(el);
  }
}

void toStruct_SignalHeadLocationList(const srem_ts_msgs::SignalHeadLocationList& in, srem_ts_SignalHeadLocationList_t& out) {
  memset(&out, 0, sizeof(srem_ts_SignalHeadLocationList_t));
  for (int i = 0; i < in.array.size(); ++i) {
    srem_ts_SignalHeadLocation_t* el = (srem_ts_SignalHeadLocation_t*) calloc(1, sizeof(srem_ts_SignalHeadLocation_t));
    toStruct_SignalHeadLocation(in.array[i], *el);
    if (asn_sequence_add(&out, el)) throw std::invalid_argument("Failed to add to A_SEQUENCE_OF");
  }
}

}
