/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/SREM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  -o \
  etsi_its_conversion/etsi_its_srem_ts_conversion/include/etsi_its_srem_ts_conversion \
  -t \
  srem_ts
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
AdvisorySpeed ::= SEQUENCE {
  type        AdvisorySpeedType,
  speed       SpeedAdvice OPTIONAL,
  confidence  SpeedConfidenceDSRC OPTIONAL,
  distance    ZoneLength OPTIONAL,
  class       RestrictionClassID OPTIONAL,
  regional    SEQUENCE (SIZE(1..4)) OF 
              RegionalExtension {{Reg-AdvisorySpeed}} OPTIONAL,
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_srem_ts_coding/srem_ts_AdvisorySpeed.h>
#include <etsi_its_srem_ts_conversion/convertAdvisorySpeedType.h>
#include <etsi_its_srem_ts_conversion/convertRestrictionClassID.h>
#include <etsi_its_srem_ts_conversion/convertSpeedAdvice.h>
#include <etsi_its_srem_ts_conversion/convertSpeedConfidenceDSRC.h>
#include <etsi_its_srem_ts_conversion/convertZoneLength.h>
#include <etsi_its_srem_ts_msgs/msg/advisory_speed.hpp>
namespace srem_ts_msgs = etsi_its_srem_ts_msgs::msg;


namespace etsi_its_srem_ts_conversion {

void toRos_AdvisorySpeed(const srem_ts_AdvisorySpeed_t& in, srem_ts_msgs::AdvisorySpeed& out) {
  toRos_AdvisorySpeedType(in.type, out.type);
  if (in.speed) {
    toRos_SpeedAdvice(*in.speed, out.speed);
    out.speed_is_present = true;
  }
  if (in.confidence) {
    toRos_SpeedConfidenceDSRC(*in.confidence, out.confidence);
    out.confidence_is_present = true;
  }
  if (in.distance) {
    toRos_ZoneLength(*in.distance, out.distance);
    out.distance_is_present = true;
  }
  if (in.Class) {
    toRos_RestrictionClassID(*in.Class, out.cls);
    out.cls_is_present = true;
  }
}

void toStruct_AdvisorySpeed(const srem_ts_msgs::AdvisorySpeed& in, srem_ts_AdvisorySpeed_t& out) {
  memset(&out, 0, sizeof(srem_ts_AdvisorySpeed_t));
  toStruct_AdvisorySpeedType(in.type, out.type);
  if (in.speed_is_present) {
    out.speed = (srem_ts_SpeedAdvice_t*) calloc(1, sizeof(srem_ts_SpeedAdvice_t));
    toStruct_SpeedAdvice(in.speed, *out.speed);
  }
  if (in.confidence_is_present) {
    out.confidence = (srem_ts_SpeedConfidenceDSRC_t*) calloc(1, sizeof(srem_ts_SpeedConfidenceDSRC_t));
    toStruct_SpeedConfidenceDSRC(in.confidence, *out.confidence);
  }
  if (in.distance_is_present) {
    out.distance = (srem_ts_ZoneLength_t*) calloc(1, sizeof(srem_ts_ZoneLength_t));
    toStruct_ZoneLength(in.distance, *out.distance);
  }
  if (in.cls_is_present) {
    out.Class = (srem_ts_RestrictionClassID_t*) calloc(1, sizeof(srem_ts_RestrictionClassID_t));
    toStruct_RestrictionClassID(in.cls, *out.Class);
  }
}

}
