/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/is_ts103301/SREM-PDU-Descriptions.asn \
  asn1/raw/is_ts103301/cdd/ITS-Container.asn \
  asn1/raw/is_ts103301/iso-patched/ISO24534-3_ElectronicRegistrationIdentificationVehicleDataModule-patched.asn \
  asn1/raw/is_ts103301/build/asn1/ISO-TS-19091-addgrp-C-2018-patched.asn \
  asn1/patched/is_ts103301/build/asn1/ISO14816_AVIAEINumberingAndDataStructures.asn \
  -o \
  etsi_its_conversion/etsi_its_srem_ts_conversion/include/etsi_its_srem_ts_conversion \
  -t \
  srem_ts
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
NodeListXY ::= CHOICE {
  nodes     NodeSetXY,
  computed  ComputedLane,
  ...
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_srem_ts_coding/srem_ts_NodeListXY.h>
#include <etsi_its_srem_ts_conversion/convertComputedLane.h>
#include <etsi_its_srem_ts_conversion/convertNodeSetXY.h>
#include <etsi_its_srem_ts_msgs/msg/node_list_xy.hpp>
namespace srem_ts_msgs = etsi_its_srem_ts_msgs::msg;


namespace etsi_its_srem_ts_conversion {

void toRos_NodeListXY(const srem_ts_NodeListXY_t& in, srem_ts_msgs::NodeListXY& out) {
  switch (in.present) {
  case srem_ts_NodeListXY_PR_nodes:
    toRos_NodeSetXY(in.choice.nodes, out.nodes);
    out.choice = srem_ts_msgs::NodeListXY::CHOICE_NODES;
    break;
  case srem_ts_NodeListXY_PR_computed:
    toRos_ComputedLane(in.choice.computed, out.computed);
    out.choice = srem_ts_msgs::NodeListXY::CHOICE_COMPUTED;
    break;
  default: break;
  }
}

void toStruct_NodeListXY(const srem_ts_msgs::NodeListXY& in, srem_ts_NodeListXY_t& out) {
  memset(&out, 0, sizeof(srem_ts_NodeListXY_t));
  switch (in.choice) {
  case srem_ts_msgs::NodeListXY::CHOICE_NODES:
    toStruct_NodeSetXY(in.nodes, out.choice.nodes);
    out.present = srem_ts_NodeListXY_PR::srem_ts_NodeListXY_PR_nodes;
    break;
  case srem_ts_msgs::NodeListXY::CHOICE_COMPUTED:
    toStruct_ComputedLane(in.computed, out.choice.computed);
    out.present = srem_ts_NodeListXY_PR::srem_ts_NodeListXY_PR_computed;
    break;
  default: break;
  }
}

}
